/*
Credit to WikiBooks for Initial data from http://en.wikibooks.org/wiki/Guitar/Chords/Full_List_Standard_Tuning
Credit to Mr Data Converter for Conversion http://shancarter.github.io/mr-data-converter/
*/
var chords = [{"Name":"A or Amaj ","Pattern":"0 4 x 2 5 0","Notes":"Db E A","Type":"major triad"},
{"Name":"A or Amaj ","Pattern":"5 7 7 6 5 5","Notes":"Db E A","Type":"major triad"},
{"Name":"A or Amaj ","Pattern":"x 0 2 2 2 0","Notes":"Db E A","Type":"major triad"},
{"Name":"A or Amaj ","Pattern":"x 4 7 x x 5","Notes":"Db E A","Type":"major triad"},
{"Name":"A #5 or Aaug ","Pattern":"x 0 3 2 2 1","Notes":"Db F A","Type":"augmented triad"},
{"Name":"A #5 or Aaug ","Pattern":"x 0 x 2 2 1","Notes":"Db F A","Type":"augmented triad"},
{"Name":"A/Ab ","Pattern":"x 0 2 1 2 0","Notes":"Db E Ab A","Type":"major triad (altered bass)"},
{"Name":"A/B ","Pattern":"0 0 2 4 2 0","Notes":"Db E A B","Type":"major triad (altered bass)"},
{"Name":"A/B ","Pattern":"x 0 7 6 0 0","Notes":"Db E A B","Type":"major triad (altered bass)"},
{"Name":"A/D ","Pattern":"x 0 0 2 2 0","Notes":"Db D E A","Type":"major triad (altered bass)"},
{"Name":"A/D ","Pattern":"x x 0 2 2 0","Notes":"Db D E A","Type":"major triad (altered bass)"},
{"Name":"A/D ","Pattern":"x x 0 6 5 5","Notes":"Db D E A","Type":"major triad (altered bass)"},
{"Name":"A/D ","Pattern":"x x 0 9 10 9","Notes":"Db D E A","Type":"major triad (altered bass)"},
{"Name":"A/G ","Pattern":"3 x 2 2 2 0","Notes":"Db E G A","Type":"major triad (altered bass)"},
{"Name":"A/G ","Pattern":"x 0 2 0 2 0","Notes":"Db E G A","Type":"major triad (altered bass)"},
{"Name":"A/G ","Pattern":"x 0 2 2 2 3","Notes":"Db E G A","Type":"major triad (altered bass)"},
{"Name":"A/Gb ","Pattern":"0 0 2 2 2 2","Notes":"Db E Gb A","Type":"major triad (altered bass)"},
{"Name":"A/Gb ","Pattern":"0 x 4 2 2 0","Notes":"Db E Gb A","Type":"major triad (altered bass)"},
{"Name":"A/Gb ","Pattern":"2 x 2 2 2 0","Notes":"Db E Gb A","Type":"major triad (altered bass)"},
{"Name":"A/Gb ","Pattern":"x 0 4 2 2 0","Notes":"Db E Gb A","Type":"major triad (altered bass)"},
{"Name":"A/Gb ","Pattern":"x x 2 2 2 2","Notes":"Db E Gb A","Type":"major triad (altered bass)"},
{"Name":"A5 or A(no 3rd) ","Pattern":"5 7 7 x x 5","Notes":"E A","Type":"root and 5th (power chord)"},
{"Name":"A5 or A(no 3rd) ","Pattern":"x 0 2 2 x 0","Notes":"E A","Type":"root and 5th (power chord)"},
{"Name":"A5 or A(no 3rd) ","Pattern":"5 7 7 x x 0","Notes":"E A","Type":"root and 5th (power chord)"},
{"Name":"A6 ","Pattern":"0 0 2 2 2 2","Notes":"Db E Gb A","Type":"major triad plus 6th"},
{"Name":"A6 ","Pattern":"0 x 4 2 2 0","Notes":"Db E Gb A","Type":"major triad plus 6th"},
{"Name":"A6 ","Pattern":"2 x 2 2 2 0","Notes":"Db E Gb A","Type":"major triad plus 6th"},
{"Name":"A6 ","Pattern":"x 0 4 2 2 0","Notes":"Db E Gb A","Type":"major triad plus 6th"},
{"Name":"A6 ","Pattern":"x x 2 2 2 2","Notes":"Db E Gb A","Type":"major triad plus 6th"},
{"Name":"A6/7 ","Pattern":"0 0 2 0 2 2","Notes":"Db E Gb G A","Type":"major triad plus 6th minor 7th"},
{"Name":"A6/7 sus or A6/7 sus4 ","Pattern":"5 5 4 0 3 0","Notes":"D E Gb G A","Type":"sus4 triad plus 6th minor 7th"},
{"Name":"A6/7 sus or A6/7 sus4 ","Pattern":"x 0 2 0 3 2","Notes":"D E Gb G A","Type":"sus4 triad plus 6th minor 7th"},
{"Name":"A7 or Adom 7 ","Pattern":"3 x 2 2 2 0","Notes":"Db E G A","Type":"major triad minor 7th"},
{"Name":"A7 or Adom 7 ","Pattern":"x 0 2 0 2 0","Notes":"Db E G A","Type":"major triad minor 7th"},
{"Name":"A7 or Adom 7 ","Pattern":"x 0 2 2 2 3","Notes":"Db E G A","Type":"major triad minor 7th"},
{"Name":"A7(#5) ","Pattern":"1 0 3 0 2 1","Notes":"Db F G A","Type":"minor 7th sharp 5th"},
{"Name":"A7/add11 or A7/11 ","Pattern":"x 0 0 0 2 0","Notes":"Db D E G A","Type":"major triad minor 7th plus 11th"},
{"Name":"A7sus4 ","Pattern":"x 0 2 0 3 0","Notes":"D E G A","Type":"sus4 triad minor 7th"},
{"Name":"A7sus4 ","Pattern":"x 0 2 0 3 3","Notes":"D E G A","Type":"sus4 triad minor 7th"},
{"Name":"A7sus4 ","Pattern":"x 0 2 2 3 3","Notes":"D E G A","Type":"sus4 triad minor 7th"},
{"Name":"A7sus4 ","Pattern":"5 x 0 0 3 0","Notes":"D E G A","Type":"sus4 triad minor 7th"},
{"Name":"A7sus4 ","Pattern":"x 0 0 0 x 0","Notes":"D E G A","Type":"sus4 triad minor 7th"},
{"Name":"Aadd9 or A2 ","Pattern":"0 0 2 4 2 0","Notes":"Db E A B","Type":"major triad plus 9th"},
{"Name":"Aadd9 or A2 ","Pattern":"x 0 7 6 0 0","Notes":"Db E A B","Type":"major triad plus 9th"},
{"Name":"Aaug/D ","Pattern":"x x 0 2 2 1","Notes":"Db D F A","Type":"augmented triad (altered bass)"},
{"Name":"Aaug/G ","Pattern":"1 0 3 0 2 1","Notes":"Db F G A","Type":"augmented triad (altered bass)"},
{"Name":"Ab or Abmaj ","Pattern":"4 6 6 5 4 4","Notes":"C Eb Ab","Type":"major triad"},
{"Name":"Ab #5 or Abaug ","Pattern":"x 3 2 1 1 0","Notes":"C E Ab","Type":"augmented triad"},
{"Name":"Ab/A ","Pattern":"x x 1 2 1 4","Notes":"C Eb Ab A","Type":"major triad (altered bass)"},
{"Name":"Ab/F ","Pattern":"x 8 10 8 9 8","Notes":"C Eb F Ab","Type":"major triad (altered bass)"},
{"Name":"Ab/F ","Pattern":"x x 1 1 1 1","Notes":"C Eb F Ab","Type":"major triad (altered bass)"},
{"Name":"Ab/Gb ","Pattern":"x x 1 1 1 2","Notes":"C Eb Gb Ab","Type":"major triad (altered bass)"},
{"Name":"Ab/Gb ","Pattern":"x x 4 5 4 4","Notes":"C Eb Gb Ab","Type":"major triad (altered bass)"},
{"Name":"Ab5 or Ab(no 3rd)","Pattern":"4 6 6 x x 4","Notes":"Eb Ab","Type":"root and 5th (power chord)"},
{"Name":"Ab6 ","Pattern":"x 8 10 8 9 8","Notes":"C Eb F Ab","Type":"major triad plus 6th"},
{"Name":"Ab6 ","Pattern":"x x 1 1 1 1","Notes":"C Eb F Ab","Type":"major triad plus 6th"},
{"Name":"Ab7 or Abdom 7 ","Pattern":"x x 1 1 1 2","Notes":"C Eb Gb Ab","Type":"major triad minor 7th"},
{"Name":"Ab7 or Abdom 7 ","Pattern":"x x 4 5 4 4","Notes":"C Eb Gb Ab","Type":"major triad minor 7th"},
{"Name":"Abdim/E ","Pattern":"0 2 0 1 0 0","Notes":"D E Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Abdim/E ","Pattern":"0 2 2 1 3 0","Notes":"D E Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Abdim/E ","Pattern":"x 2 0 1 3 0","Notes":"D E Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Abdim/E ","Pattern":"x x 0 1 0 0","Notes":"D E Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Abdim/Eb ","Pattern":"x x 0 4 4 4","Notes":"D Eb Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Abdim/F ","Pattern":"x 2 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Abdim/F ","Pattern":"x x 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Abdim/F ","Pattern":"x x 3 4 3 4","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Abdim7 ","Pattern":"x 2 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Abdim7 ","Pattern":"x x 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Abdim7 ","Pattern":"x x 3 4 3 4","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Abm ","Pattern":"x x 6 4 4 4","Notes":"Eb Ab B","Type":"minor triad"},
{"Name":"Abm/D ","Pattern":"x x 0 4 4 4","Notes":"D Eb Ab B","Type":"minor triad (altered bass)"},
{"Name":"Abm/E ","Pattern":"0 2 1 1 0 0","Notes":"Eb E Ab B","Type":"minor triad (altered bass)"},
{"Name":"Abm/E ","Pattern":"0 x 6 4 4 0","Notes":"Eb E Ab B","Type":"minor triad (altered bass)"},
{"Name":"Abm/E ","Pattern":"x x 1 1 0 0","Notes":"Eb E Ab B","Type":"minor triad (altered bass)"},
{"Name":"Abm/Gb ","Pattern":"x x 4 4 4 4","Notes":"Eb Gb Ab B","Type":"minor triad (altered bass)"},
{"Name":"Abm7 ","Pattern":"x x 4 4 4 4","Notes":"Eb Gb Ab B","Type":"minor triad minor 7th"},
{"Name":"Absus or Absus4 ","Pattern":"x x 6 6 4 4","Notes":"Db Eb Ab","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Absus2/F ","Pattern":"x 1 3 1 4 1","Notes":"Eb F Ab Bb","Type":"sus2 triad (altered bass)"},
{"Name":"Adim/Ab ","Pattern":"x x 1 2 1 4","Notes":"C Eb Ab A","Type":"diminished triad (altered bass)"},
{"Name":"Adim/E ","Pattern":"0 3 x 2 4 0","Notes":"C Eb E A","Type":"diminished triad (altered bass)"},
{"Name":"Adim/F ","Pattern":"x x 1 2 1 1","Notes":"C Eb F A","Type":"diminished triad (altered bass)"},
{"Name":"Adim/F ","Pattern":"x x 3 5 4 5","Notes":"C Eb F A","Type":"diminished triad (altered bass)"},
{"Name":"Adim/G ","Pattern":"x x 1 2 1 3","Notes":"C Eb G A","Type":"diminished triad (altered bass)"},
{"Name":"Adim/Gb ","Pattern":"x x 1 2 1 2","Notes":"C Eb Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Adim7 ","Pattern":"x x 1 2 1 2","Notes":"C Eb Gb A","Type":"diminished triad diminished 7th"},
{"Name":"Am ","Pattern":"x 0 2 2 1 0","Notes":"C E A","Type":"minor triad"},
{"Name":"Am ","Pattern":"x 0 7 5 5 5","Notes":"C E A","Type":"minor triad"},
{"Name":"Am ","Pattern":"x 3 2 2 1 0","Notes":"C E A","Type":"minor triad"},
{"Name":"Am ","Pattern":"8 12 x x x 0","Notes":"C E A","Type":"minor triad"},
{"Name":"Am/B ","Pattern":"0 0 7 5 0 0","Notes":"C E A B","Type":"minor triad (altered bass)"},
{"Name":"Am/B ","Pattern":"x 3 2 2 0 0","Notes":"C E A B","Type":"minor triad (altered bass)"},
{"Name":"Am/D ","Pattern":"x x 0 2 1 0","Notes":"C D E A","Type":"minor triad (altered bass)"},
{"Name":"Am/D ","Pattern":"x x 0 5 5 5","Notes":"C D E A","Type":"minor triad (altered bass)"},
{"Name":"Am/Eb ","Pattern":"0 3 x 2 4 0","Notes":"C Eb E A","Type":"minor triad (altered bass)"},
{"Name":"Am/F ","Pattern":"0 0 3 2 1 0","Notes":"C E F A","Type":"minor triad (altered bass)"},
{"Name":"Am/F ","Pattern":"1 3 3 2 1 0","Notes":"C E F A","Type":"minor triad (altered bass)"},
{"Name":"Am/F ","Pattern":"1 x 2 2 1 0","Notes":"C E F A","Type":"minor triad (altered bass)"},
{"Name":"Am/F ","Pattern":"x x 2 2 1 1","Notes":"C E F A","Type":"minor triad (altered bass)"},
{"Name":"Am/F ","Pattern":"x x 3 2 1 0","Notes":"C E F A","Type":"minor triad (altered bass)"},
{"Name":"Am/G ","Pattern":"0 0 2 0 1 3","Notes":"C E G A","Type":"minor triad (altered bass)"},
{"Name":"Am/G ","Pattern":"x 0 2 0 1 0","Notes":"C E G A","Type":"minor triad (altered bass)"},
{"Name":"Am/G ","Pattern":"x 0 2 2 1 3","Notes":"C E G A","Type":"minor triad (altered bass)"},
{"Name":"Am/G ","Pattern":"x 0 5 5 5 8","Notes":"C E G A","Type":"minor triad (altered bass)"},
{"Name":"Am/Gb ","Pattern":"x 0 2 2 1 2","Notes":"C E Gb A","Type":"minor triad (altered bass)"},
{"Name":"Am/Gb ","Pattern":"x x 2 2 1 2","Notes":"C E Gb A","Type":"minor triad (altered bass)"},
{"Name":"Am6 ","Pattern":"x 0 2 2 1 2","Notes":"C E Gb A","Type":"minor triad plus 6th"},
{"Name":"Am6 ","Pattern":"x x 2 2 1 2","Notes":"C E Gb A","Type":"minor triad plus 6th"},
{"Name":"Am7 ","Pattern":"0 0 2 0 1 3","Notes":"C E G A","Type":"minor triad minor 7th"},
{"Name":"Am7 ","Pattern":"x 0 2 0 1 0","Notes":"C E G A","Type":"minor triad minor 7th"},
{"Name":"Am7 ","Pattern":"x 0 2 2 1 3","Notes":"C E G A","Type":"minor triad minor 7th"},
{"Name":"Am7 ","Pattern":"x 0 5 5 5 8","Notes":"C E G A","Type":"minor triad minor 7th"},
{"Name":"Am7(b5) or Ao7 ","Pattern":"x x 1 2 1 3","Notes":"C Eb G A","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Am7/add11 or Am7/11 ","Pattern":"x 5 7 5 8 0","Notes":"C D E G A","Type":"minor triad minor 7th plus 11th"},
{"Name":"Amaj7 or A#7 ","Pattern":"x 0 2 1 2 0","Notes":"Db E Ab A","Type":"major triad major 7th"},
{"Name":"Amin/maj9 ","Pattern":"x 0 6 5 5 7","Notes":"C E Ab A B","Type":"minor triad major 7th plus 9th"},
{"Name":"Asus or Asus4 ","Pattern":"0 0 2 2 3 0","Notes":"D E A","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Asus or Asus4 ","Pattern":"x 0 2 2 3 0","Notes":"D E A","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Asus or Asus4 ","Pattern":"5 5 7 7 x 0","Notes":"D E A","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Asus or Asus4 ","Pattern":"x 0 0 2 3 0","Notes":"D E A","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Asus2 or Aadd9(no3)","Pattern":"0 0 2 2 0 0","Notes":"E A B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Asus2 or Aadd9(no3)","Pattern":"0 0 2 4 0 0","Notes":"E A B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Asus2 or Aadd9(no3)","Pattern":"0 2 2 2 0 0","Notes":"E A B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Asus2 or Aadd9(no3)","Pattern":"x 0 2 2 0 0","Notes":"E A B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Asus2 or Aadd9(no3)","Pattern":"x x 2 2 0 0","Notes":"E A B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Asus2/Ab ","Pattern":"x 0 2 1 0 0","Notes":"E Ab A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/C ","Pattern":"0 0 7 5 0 0","Notes":"C E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/C ","Pattern":"x 3 2 2 0 0","Notes":"C E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/D ","Pattern":"0 2 0 2 0 0","Notes":"D E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/D ","Pattern":"x 2 0 2 3 0","Notes":"D E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/Db ","Pattern":"0 0 2 4 2 0","Notes":"Db E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/Db ","Pattern":"x 0 7 6 0 0","Notes":"Db E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/Eb ","Pattern":"x 2 1 2 0 0","Notes":"Eb E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/F ","Pattern":"0 0 3 2 0 0","Notes":"E F A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/G ","Pattern":"3 x 2 2 0 0","Notes":"E G A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/G ","Pattern":"x 0 2 0 0 0","Notes":"E G A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/G ","Pattern":"x 0 5 4 5 0","Notes":"E G A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/Gb ","Pattern":"x 0 4 4 0 0","Notes":"E Gb A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus2/Gb ","Pattern":"x 2 4 2 5 2","Notes":"E Gb A B","Type":"sus2 triad (altered bass)"},
{"Name":"Asus4/Ab ","Pattern":"4 x 0 2 3 0","Notes":"D E Ab A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/B ","Pattern":"0 2 0 2 0 0","Notes":"D E A B","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Bb ","Pattern":"0 1 x 2 3 0","Notes":"D E A Bb","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/C ","Pattern":"x x 0 2 1 0","Notes":"C D E A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/C ","Pattern":"x x 0 5 5 5","Notes":"C D E A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Db ","Pattern":"x 0 0 2 2 0","Notes":"Db D E A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Db ","Pattern":"x x 0 2 2 0","Notes":"Db D E A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Db ","Pattern":"x x 0 6 5 5","Notes":"Db D E A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Db ","Pattern":"x x 0 9 10 9","Notes":"Db D E A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/F ","Pattern":"x x 7 7 6 0","Notes":"D E F A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/G ","Pattern":"x 0 2 0 3 0","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/G ","Pattern":"x 0 2 0 3 3","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/G ","Pattern":"x 0 2 2 3 3","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/G ","Pattern":"x 0 0 0 x 0","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Gb ","Pattern":"0 0 0 2 3 2","Notes":"D E Gb A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Gb ","Pattern":"0 0 4 2 3 0","Notes":"D E Gb A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Gb ","Pattern":"2 x 0 2 3 0","Notes":"D E Gb A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Gb ","Pattern":"x 0 2 2 3 2","Notes":"D E Gb A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Gb ","Pattern":"x x 2 2 3 2","Notes":"D E Gb A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Gb ","Pattern":"x 5 4 2 3 0","Notes":"D E Gb A","Type":"sus4 triad (altered bass)"},
{"Name":"Asus4/Gb ","Pattern":"x 9 7 7 x 0","Notes":"D E Gb A","Type":"sus4 triad (altered bass)"},
{"Name":"B or Bmaj ","Pattern":"x 2 4 4 4 2","Notes":"Eb Gb B","Type":"major triad"},
{"Name":"B #5 or Baug ","Pattern":"3 2 1 0 0 3","Notes":"Eb G B","Type":"augmented triad"},
{"Name":"B #5 or Baug ","Pattern":"3 x 1 0 0 3","Notes":"Eb G B","Type":"augmented triad"},
{"Name":"B/A ","Pattern":"2 x 1 2 0 2","Notes":"Eb Gb A B","Type":"major triad (altered bass)"},
{"Name":"B/A ","Pattern":"x 0 1 2 0 2","Notes":"Eb Gb A B","Type":"major triad (altered bass)"},
{"Name":"B/A ","Pattern":"x 2 1 2 0 2","Notes":"Eb Gb A B","Type":"major triad (altered bass)"},
{"Name":"B/A ","Pattern":"x 2 4 2 4 2","Notes":"Eb Gb A B","Type":"major triad (altered bass)"},
{"Name":"B/Ab ","Pattern":"x x 4 4 4 4","Notes":"Eb Gb Ab B","Type":"major triad (altered bass)"},
{"Name":"B/E ","Pattern":"x 2 2 4 4 2","Notes":"Eb E Gb B","Type":"major triad (altered bass)"},
{"Name":"B/E ","Pattern":"x x 4 4 4 0","Notes":"Eb E Gb B","Type":"major triad (altered bass)"},
{"Name":"B5 or B(no 3rd) ","Pattern":"7 9 9 x x 2","Notes":"Gb B","Type":"root and 5th (power chord)"},
{"Name":"B5 or B(no 3rd) ","Pattern":"x 2 4 4 x 2","Notes":"Gb B","Type":"root and 5th (power chord)"},
{"Name":"B6 ","Pattern":"x x 4 4 4 4","Notes":"Eb Gb Ab B","Type":"major triad plus 6th"},
{"Name":"B7 or Bdom 7 ","Pattern":"2 x 1 2 0 2","Notes":"Eb Gb A B","Type":"major triad minor 7th"},
{"Name":"B7 or Bdom 7 ","Pattern":"x 0 1 2 0 2","Notes":"Eb Gb A B","Type":"major triad minor 7th"},
{"Name":"B7 or Bdom 7 ","Pattern":"x 2 1 2 0 2","Notes":"Eb Gb A B","Type":"major triad minor 7th"},
{"Name":"B7 or Bdom 7 ","Pattern":"x 2 4 2 4 2","Notes":"Eb Gb A B","Type":"major triad minor 7th"},
{"Name":"B7/add11 or B7/11 ","Pattern":"0 0 4 4 4 0","Notes":"Eb E Gb A B","Type":"major triad minor 7th plus 11th"},
{"Name":"B7/add11 or B7/11 ","Pattern":"0 2 1 2 0 2","Notes":"Eb E Gb A B","Type":"major triad minor 7th plus 11th"},
{"Name":"B7sus4 ","Pattern":"x 0 4 4 0 0","Notes":"E Gb A B","Type":"sus4 triad minor 7th"},
{"Name":"B7sus4 ","Pattern":"x 2 4 2 5 2","Notes":"E Gb A B","Type":"sus4 triad minor 7th"},
{"Name":"Baug/E ","Pattern":"3 x 1 0 0 0","Notes":"Eb E G B","Type":"augmented triad (altered bass)"},
{"Name":"Baug/E ","Pattern":"x x 1 0 0 0","Notes":"Eb E G B","Type":"augmented triad (altered bass)"},
{"Name":"Bb or Bbmaj ","Pattern":"1 1 3 3 3 1","Notes":"D F Bb","Type":"major triad"},
{"Name":"Bb or Bbmaj ","Pattern":"x 1 3 3 3 1","Notes":"D F Bb","Type":"major triad"},
{"Name":"Bb or Bbmaj ","Pattern":"x x 0 3 3 1","Notes":"D F Bb","Type":"major triad"},
{"Name":"Bb #5 or Bbaug ","Pattern":"x x 0 3 3 2","Notes":"D Gb Bb","Type":"augmented triad"},
{"Name":"Bb b5 ","Pattern":"x x 0 3 x 0","Notes":"D E Bb","Type":"flat 5th"},
{"Name":"Bb/A ","Pattern":"1 1 3 2 3 1","Notes":"D F A Bb","Type":"major triad (altered bass)"},
{"Name":"Bb/Ab ","Pattern":"x 1 3 1 3 1","Notes":"D F Ab Bb","Type":"major triad (altered bass)"},
{"Name":"Bb/Ab ","Pattern":"x x 3 3 3 4","Notes":"D F Ab Bb","Type":"major triad (altered bass)"},
{"Name":"Bb/Db ","Pattern":"x x 0 6 6 6","Notes":"Db D F Bb","Type":"major triad (altered bass)"},
{"Name":"Bb/E ","Pattern":"x 1 3 3 3 0","Notes":"D E F Bb","Type":"major triad (altered bass)"},
{"Name":"Bb/G ","Pattern":"3 5 3 3 3 3","Notes":"D F G Bb","Type":"major triad (altered bass)"},
{"Name":"Bb/G ","Pattern":"x x 3 3 3 3","Notes":"D F G Bb","Type":"major triad (altered bass)"},
{"Name":"Bb5 or Bb(no 3rd)","Pattern":"6 8 8 x x 6","Notes":"F Bb","Type":"root and 5th (power chord)"},
{"Name":"Bb5 or Bb(no 3rd)","Pattern":"x 1 3 3 x 6","Notes":"F Bb","Type":"root and 5th (power chord)"},
{"Name":"Bb6 ","Pattern":"3 5 3 3 3 3","Notes":"D F G Bb","Type":"major triad plus 6th"},
{"Name":"Bb6 ","Pattern":"x x 3 3 3 3","Notes":"D F G Bb","Type":"major triad plus 6th"},
{"Name":"Bb6/add9 or Bb6/9 ","Pattern":"x 3 3 3 3 3","Notes":"C D F G Bb","Type":"major triad plus 6th and 9th"},
{"Name":"Bb7 or Bbdom 7 ","Pattern":"x 1 3 1 3 1","Notes":"D F Ab Bb","Type":"major triad minor 7th"},
{"Name":"Bb7 or Bbdom 7 ","Pattern":"x x 3 3 3 4","Notes":"D F Ab Bb","Type":"major triad minor 7th"},
{"Name":"Bb7sus4 ","Pattern":"x 1 3 1 4 1","Notes":"Eb F Ab Bb","Type":"sus4 triad minor 7th"},
{"Name":"Bbadd#11 ","Pattern":"x 1 3 3 3 0","Notes":"D E F Bb","Type":"major triad augmented 11th"},
{"Name":"Bbaug/E ","Pattern":"2 x 4 3 3 0","Notes":"D E Gb Bb","Type":"augmented triad (altered bass)"},
{"Name":"Bbdim/C ","Pattern":"x 3 x 3 2 0","Notes":"C Db E Bb","Type":"diminished triad (altered bass)"},
{"Name":"Bbdim/D ","Pattern":"x x 0 3 2 0","Notes":"Db D E Bb","Type":"diminished triad (altered bass)"},
{"Name":"Bbdim/G ","Pattern":"x 1 2 0 2 0","Notes":"Db E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Bbdim/G ","Pattern":"x x 2 3 2 3","Notes":"Db E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Bbdim/Gb ","Pattern":"2 4 2 3 2 2","Notes":"Db E Gb Bb","Type":"diminished triad (altered bass)"},
{"Name":"Bbdim/Gb ","Pattern":"x x 4 3 2 0","Notes":"Db E Gb Bb","Type":"diminished triad (altered bass)"},
{"Name":"Bbdim7 ","Pattern":"x 1 2 0 2 0","Notes":"Db E G Bb","Type":"diminished triad diminished 7th"},
{"Name":"Bbdim7 ","Pattern":"x x 2 3 2 3","Notes":"Db E G Bb","Type":"diminished triad diminished 7th"},
{"Name":"Bbm ","Pattern":"1 1 3 3 2 1","Notes":"Db F Bb","Type":"minor triad"},
{"Name":"Bbm/Ab ","Pattern":"x 1 3 1 2 1","Notes":"Db F Ab Bb","Type":"minor triad (altered bass)"},
{"Name":"Bbm/D ","Pattern":"x x 0 6 6 6","Notes":"Db D F Bb","Type":"minor triad (altered bass)"},
{"Name":"Bbm/Gb ","Pattern":"x x 3 3 2 2","Notes":"Db F Gb Bb","Type":"minor triad (altered bass)"},
{"Name":"Bbm7 ","Pattern":"x 1 3 1 2 1","Notes":"Db F Ab Bb","Type":"minor triad minor 7th"},
{"Name":"Bbmaj7 or Bb#7 ","Pattern":"1 1 3 2 3 1","Notes":"D F A Bb","Type":"major triad major 7th"},
{"Name":"Bbmaj9 or Bb9(#7) ","Pattern":"x 3 3 3 3 5","Notes":"C D F A Bb","Type":"major triad major 7th plus 9th"},
{"Name":"Bbsus2 or Bbadd9(no3)","Pattern":"x x 3 3 1 1","Notes":"C F Bb","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Bbsus2/G ","Pattern":"x 3 5 3 6 3","Notes":"C F G Bb","Type":"sus2 triad (altered bass)"},
{"Name":"Bbsus4/Ab ","Pattern":"x 1 3 1 4 1","Notes":"Eb F Ab Bb","Type":"sus4 triad (altered bass)"},
{"Name":"Bdim/A ","Pattern":"1 2 3 2 3 1","Notes":"D F A B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim/A ","Pattern":"x 2 0 2 0 1","Notes":"D F A B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim/A ","Pattern":"x x 0 2 0 1","Notes":"D F A B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim/Ab ","Pattern":"x 2 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim/Ab ","Pattern":"x x 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim/Ab ","Pattern":"x x 3 4 3 4","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim/G ","Pattern":"1 x 0 0 0 3","Notes":"D F G B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim/G ","Pattern":"3 2 0 0 0 1","Notes":"D F G B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim/G ","Pattern":"x x 0 0 0 1","Notes":"D F G B","Type":"diminished triad (altered bass)"},
{"Name":"Bdim7 ","Pattern":"x 2 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Bdim7 ","Pattern":"x x 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Bdim7 ","Pattern":"x x 3 4 3 4","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Bm ","Pattern":"2 2 4 4 3 2","Notes":"D Gb B","Type":"minor triad"},
{"Name":"Bm ","Pattern":"x 2 4 4 3 2","Notes":"D Gb B","Type":"minor triad"},
{"Name":"Bm ","Pattern":"x x 0 4 3 2","Notes":"D Gb B","Type":"minor triad"},
{"Name":"Bm/A ","Pattern":"x 0 4 4 3 2","Notes":"D Gb A B","Type":"minor triad (altered bass)"},
{"Name":"Bm/A ","Pattern":"x 2 0 2 0 2","Notes":"D Gb A B","Type":"minor triad (altered bass)"},
{"Name":"Bm/A ","Pattern":"x 2 0 2 3 2","Notes":"D Gb A B","Type":"minor triad (altered bass)"},
{"Name":"Bm/A ","Pattern":"x 2 4 2 3 2","Notes":"D Gb A B","Type":"minor triad (altered bass)"},
{"Name":"Bm/A ","Pattern":"x x 0 2 0 2","Notes":"D Gb A B","Type":"minor triad (altered bass)"},
{"Name":"Bm/G ","Pattern":"2 2 0 0 0 3","Notes":"D Gb G B","Type":"minor triad (altered bass)"},
{"Name":"Bm/G ","Pattern":"2 2 0 0 3 3","Notes":"D Gb G B","Type":"minor triad (altered bass)"},
{"Name":"Bm/G ","Pattern":"3 2 0 0 0 2","Notes":"D Gb G B","Type":"minor triad (altered bass)"},
{"Name":"Bm/G ","Pattern":"x x 4 4 3 3","Notes":"D Gb G B","Type":"minor triad (altered bass)"},
{"Name":"Bm7 ","Pattern":"x 0 4 4 3 2","Notes":"D Gb A B","Type":"minor triad minor 7th"},
{"Name":"Bm7 ","Pattern":"x 2 0 2 0 2","Notes":"D Gb A B","Type":"minor triad minor 7th"},
{"Name":"Bm7 ","Pattern":"x 2 0 2 3 2","Notes":"D Gb A B","Type":"minor triad minor 7th"},
{"Name":"Bm7 ","Pattern":"x 2 4 2 3 2","Notes":"D Gb A B","Type":"minor triad minor 7th"},
{"Name":"Bm7 ","Pattern":"x x 0 2 0 2","Notes":"D Gb A B","Type":"minor triad minor 7th"},
{"Name":"Bm7(b5) or Bo7 ","Pattern":"1 2 3 2 3 1","Notes":"D F A B","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Bm7(b5) or Bo7 ","Pattern":"x 2 0 2 0 1","Notes":"D F A B","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Bm7(b5) or Bo7 ","Pattern":"x x 0 2 0 1","Notes":"D F A B","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Bm7/add11 or Bm7/11 ","Pattern":"0 0 2 4 3 2","Notes":"D E Gb A B","Type":"minor triad minor 7th plus 11th"},
{"Name":"Bm7/add11 or Bm7/11 ","Pattern":"0 2 0 2 0 2","Notes":"D E Gb A B","Type":"minor triad minor 7th plus 11th"},
{"Name":"Bmaj7/#11 ","Pattern":"x 2 3 3 4 2","Notes":"Eb F Gb Bb B","Type":"major triad major 7th augmented 11th"},
{"Name":"Bsus or Bsus4 ","Pattern":"7 9 9 x x 0","Notes":"E Gb B","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Bsus or Bsus4 ","Pattern":"x 2 4 4 x 0","Notes":"E Gb B","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Bsus2 or Badd9(no3)","Pattern":"x 4 4 4 x 2","Notes":"Db Gb B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Bsus2 or Badd9(no3)","Pattern":"x x 4 4 2 2","Notes":"Db Gb B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Bsus2/E ","Pattern":"x 4 4 4 x 0","Notes":"Db E Gb B","Type":"sus2 triad (altered bass)"},
{"Name":"Bsus4/A ","Pattern":"x 0 4 4 0 0","Notes":"E Gb A B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/A ","Pattern":"x 2 4 2 5 2","Notes":"E Gb A B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/Ab ","Pattern":"0 2 2 1 0 2","Notes":"E Gb Ab B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/Ab ","Pattern":"0 x 4 1 0 0","Notes":"E Gb Ab B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/Ab ","Pattern":"2 2 2 1 0 0","Notes":"E Gb Ab B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/Db ","Pattern":"x 4 4 4 x 0","Notes":"Db E Gb B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/Eb ","Pattern":"x 2 2 4 4 2","Notes":"Eb E Gb B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/Eb ","Pattern":"x x 4 4 4 0","Notes":"Eb E Gb B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/G ","Pattern":"0 2 2 0 0 2","Notes":"E Gb G B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/G ","Pattern":"0 2 4 0 0 0","Notes":"E Gb G B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/G ","Pattern":"0 x 4 0 0 0","Notes":"E Gb G B","Type":"sus4 triad (altered bass)"},
{"Name":"Bsus4/G ","Pattern":"2 2 2 0 0 0","Notes":"E Gb G B","Type":"sus4 triad (altered bass)"},
{"Name":"C or Cmaj ","Pattern":"0 3 2 0 1 0","Notes":"C E G","Type":"major triad"},
{"Name":"C or Cmaj ","Pattern":"0 3 5 5 5 3","Notes":"C E G","Type":"major triad"},
{"Name":"C or Cmaj ","Pattern":"3 3 2 0 1 0","Notes":"C E G","Type":"major triad"},
{"Name":"C or Cmaj ","Pattern":"3 x 2 0 1 0","Notes":"C E G","Type":"major triad"},
{"Name":"C or Cmaj ","Pattern":"x 3 2 0 1 0","Notes":"C E G","Type":"major triad"},
{"Name":"C or Cmaj ","Pattern":"x 3 5 5 5 0","Notes":"C E G","Type":"major triad"},
{"Name":"C #5 or Caug ","Pattern":"x 3 2 1 1 0","Notes":"C E Ab","Type":"augmented triad"},
{"Name":"C b5 ","Pattern":"x x 4 5 x 0","Notes":"C E Gb","Type":"flat 5th"},
{"Name":"C/A ","Pattern":"0 0 2 0 1 3","Notes":"C E G A","Type":"major triad (altered bass)"},
{"Name":"C/A ","Pattern":"x 0 2 0 1 0","Notes":"C E G A","Type":"major triad (altered bass)"},
{"Name":"C/A ","Pattern":"x 0 2 2 1 3","Notes":"C E G A","Type":"major triad (altered bass)"},
{"Name":"C/A ","Pattern":"x 0 5 5 5 8","Notes":"C E G A","Type":"major triad (altered bass)"},
{"Name":"C/B ","Pattern":"0 3 2 0 0 0","Notes":"C E G B","Type":"major triad (altered bass)"},
{"Name":"C/B ","Pattern":"x 2 2 0 1 0","Notes":"C E G B","Type":"major triad (altered bass)"},
{"Name":"C/B ","Pattern":"x 3 5 4 5 3","Notes":"C E G B","Type":"major triad (altered bass)"},
{"Name":"C/Bb ","Pattern":"x 3 5 3 5 3","Notes":"C E G Bb","Type":"major triad (altered bass)"},
{"Name":"C/D ","Pattern":"3 x 0 0 1 0","Notes":"C D E G","Type":"major triad (altered bass)"},
{"Name":"C/D ","Pattern":"x 3 0 0 1 0","Notes":"C D E G","Type":"major triad (altered bass)"},
{"Name":"C/D ","Pattern":"x 3 2 0 3 0","Notes":"C D E G","Type":"major triad (altered bass)"},
{"Name":"C/D ","Pattern":"x 3 2 0 3 3","Notes":"C D E G","Type":"major triad (altered bass)"},
{"Name":"C/D ","Pattern":"x x 0 0 1 0","Notes":"C D E G","Type":"major triad (altered bass)"},
{"Name":"C/D ","Pattern":"x x 0 5 5 3","Notes":"C D E G","Type":"major triad (altered bass)"},
{"Name":"C/D ","Pattern":"x 10 12 12 13 0","Notes":"C D E G","Type":"major triad (altered bass)"},
{"Name":"C/D ","Pattern":"x 5 5 5 x 0","Notes":"C D E G","Type":"major triad (altered bass)"},
{"Name":"C/F ","Pattern":"x 3 3 0 1 0","Notes":"C E F G","Type":"major triad (altered bass)"},
{"Name":"C/F ","Pattern":"x x 3 0 1 0","Notes":"C E F G","Type":"major triad (altered bass)"},
{"Name":"C5 or C(no 3rd) ","Pattern":"x 3 5 5 x 3","Notes":"C G","Type":"root and 5th (power chord)"},
{"Name":"C6 ","Pattern":"0 0 2 0 1 3","Notes":"C E G A","Type":"major triad plus 6th"},
{"Name":"C6 ","Pattern":"x 0 2 0 1 0","Notes":"C E G A","Type":"major triad plus 6th"},
{"Name":"C6 ","Pattern":"x 0 2 2 1 3","Notes":"C E G A","Type":"major triad plus 6th"},
{"Name":"C6 ","Pattern":"x 0 5 5 5 8","Notes":"C E G A","Type":"major triad plus 6th"},
{"Name":"C6/add9 or C6/9 ","Pattern":"x 5 7 5 8 0","Notes":"C D E G A","Type":"major triad plus 6th and 9th"},
{"Name":"C7 or Cdom 7 ","Pattern":"x 3 5 3 5 3","Notes":"C E G Bb","Type":"major triad minor 7th"},
{"Name":"C7sus4 ","Pattern":"x 3 5 3 6 3","Notes":"C F G Bb","Type":"sus4 triad minor 7th"},
{"Name":"C9(b5) ","Pattern":"0 3 x 3 3 2","Notes":"C D E Gb Bb","Type":"diminished 5th minor 7th plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"3 x 0 0 1 0","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"x 3 0 0 1 0","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"x 3 2 0 3 0","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"x 3 2 0 3 3","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"x x 0 0 1 0","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"x x 0 5 5 3","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"x 10 12 12 13 0","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"x 3 2 0 3 0","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cadd9 or C2 ","Pattern":"x 5 5 5 x 0","Notes":"C D E G","Type":"major triad plus 9th"},
{"Name":"Cdim/A ","Pattern":"x x 1 2 1 2","Notes":"C Eb Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Cdim/Ab ","Pattern":"x x 1 1 1 2","Notes":"C Eb Gb Ab","Type":"diminished triad (altered bass)"},
{"Name":"Cdim/Ab ","Pattern":"x x 4 5 4 4","Notes":"C Eb Gb Ab","Type":"diminished triad (altered bass)"},
{"Name":"Cdim/D ","Pattern":"x 5 4 5 4 2","Notes":"C D Eb Gb","Type":"diminished triad (altered bass)"},
{"Name":"Cdim7 ","Pattern":"x x 1 2 1 2","Notes":"C Eb Gb A","Type":"diminished triad diminished 7th"},
{"Name":"Cm ","Pattern":"x 3 5 5 4 3","Notes":"C Eb G","Type":"minor triad"},
{"Name":"Cm ","Pattern":"x x 5 5 4 3","Notes":"C Eb G","Type":"minor triad"},
{"Name":"Cm/A ","Pattern":"x x 1 2 1 3","Notes":"C Eb G A","Type":"minor triad (altered bass)"},
{"Name":"Cm/Bb ","Pattern":"x 3 5 3 4 3","Notes":"C Eb G Bb","Type":"minor triad (altered bass)"},
{"Name":"Cm6 ","Pattern":"x x 1 2 1 3","Notes":"C Eb G A","Type":"minor triad plus 6th"},
{"Name":"Cm7 ","Pattern":"x 3 5 3 4 3","Notes":"C Eb G Bb","Type":"minor triad minor 7th"},
{"Name":"Cmaj7 or C#7 ","Pattern":"0 3 2 0 0 0","Notes":"C E G B","Type":"major triad major 7th"},
{"Name":"Cmaj7 or C#7 ","Pattern":"x 2 2 0 1 0","Notes":"C E G B","Type":"major triad major 7th"},
{"Name":"Cmaj7 or C#7 ","Pattern":"x 3 5 4 5 3","Notes":"C E G B","Type":"major triad major 7th"},
{"Name":"Cmaj9 or C9(#7) ","Pattern":"x 3 0 0 0 0","Notes":"C D E G B","Type":"major triad major 7th plus 9th"},
{"Name":"Csus or Csus4 ","Pattern":"x 3 3 0 1 1","Notes":"C F G","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Csus or Csus4 ","Pattern":"x x 3 0 1 1","Notes":"C F G","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Csus2 or Cadd9(no3)","Pattern":"x 10 12 12 13 3","Notes":"C D G","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Csus2 or Cadd9(no3)","Pattern":"x 5 5 5 x 3","Notes":"C D G","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Csus2 or Cadd9(no3)","Pattern":"x 3 0 0 3 3","Notes":"C D G","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Csus2 or Cadd9(no3)","Pattern":"x 3 5 5 3 3","Notes":"C D G","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Csus2/A ","Pattern":"x 5 7 5 8 3","Notes":"C D G A","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/A ","Pattern":"x x 0 2 1 3","Notes":"C D G A","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/B ","Pattern":"3 3 0 0 0 3","Notes":"C D G B","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/B ","Pattern":"x 3 0 0 0 3","Notes":"C D G B","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/E ","Pattern":"3 x 0 0 1 0","Notes":"C D E G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/E ","Pattern":"x 3 0 0 1 0","Notes":"C D E G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/E ","Pattern":"x 3 2 0 3 0","Notes":"C D E G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/E ","Pattern":"x 3 2 0 3 3","Notes":"C D E G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/E ","Pattern":"x x 0 0 1 0","Notes":"C D E G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/E ","Pattern":"x x 0 5 5 3","Notes":"C D E G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/E ","Pattern":"x 10 12 12 13 0","Notes":"C D E G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/E ","Pattern":"x 5 5 5 x 0","Notes":"C D E G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus2/F ","Pattern":"3 3 0 0 1 1","Notes":"C D F G","Type":"sus2 triad (altered bass)"},
{"Name":"Csus4/A ","Pattern":"3 x 3 2 1 1","Notes":"C F G A","Type":"sus4 triad (altered bass)"},
{"Name":"Csus4/A ","Pattern":"x x 3 2 1 3","Notes":"C F G A","Type":"sus4 triad (altered bass)"},
{"Name":"Csus4/B ","Pattern":"x 3 3 0 0 3","Notes":"C F G B","Type":"sus4 triad (altered bass)"},
{"Name":"Csus4/Bb ","Pattern":"x 3 5 3 6 3","Notes":"C F G Bb","Type":"sus4 triad (altered bass)"},
{"Name":"Csus4/D ","Pattern":"3 3 0 0 1 1","Notes":"C D F G","Type":"sus4 triad (altered bass)"},
{"Name":"Csus4/E ","Pattern":"x 3 3 0 1 0","Notes":"C E F G","Type":"sus4 triad (altered bass)"},
{"Name":"Csus4/E ","Pattern":"x x 3 0 1 0","Notes":"C E F G","Type":"sus4 triad (altered bass)"},
{"Name":"D or Dmaj ","Pattern":"x 5 4 2 3 2","Notes":"D Gb A","Type":"major triad"},
{"Name":"D or Dmaj ","Pattern":"x 9 7 7 x 2","Notes":"D Gb A","Type":"major triad"},
{"Name":"D or Dmaj ","Pattern":"2 0 0 2 3 2","Notes":"D Gb A","Type":"major triad"},
{"Name":"D or Dmaj ","Pattern":"x 0 0 2 3 2","Notes":"D Gb A","Type":"major triad"},
{"Name":"D or Dmaj ","Pattern":"x 0 4 2 3 2","Notes":"D Gb A","Type":"major triad"},
{"Name":"D or Dmaj ","Pattern":"x x 0 2 3 2","Notes":"D Gb A","Type":"major triad"},
{"Name":"D or Dmaj ","Pattern":"x x 0 7 7 5","Notes":"D Gb A","Type":"major triad"},
{"Name":"D #5 or Daug ","Pattern":"x x 0 3 3 2","Notes":"D Gb Bb","Type":"augmented triad"},
{"Name":"D/B ","Pattern":"x 0 4 4 3 2","Notes":"D Gb A B","Type":"major triad (altered bass)"},
{"Name":"D/B ","Pattern":"x 2 0 2 0 2","Notes":"D Gb A B","Type":"major triad (altered bass)"},
{"Name":"D/B ","Pattern":"x 2 0 2 3 2","Notes":"D Gb A B","Type":"major triad (altered bass)"},
{"Name":"D/B ","Pattern":"x 2 4 2 3 2","Notes":"D Gb A B","Type":"major triad (altered bass)"},
{"Name":"D/B ","Pattern":"x x 0 2 0 2","Notes":"D Gb A B","Type":"major triad (altered bass)"},
{"Name":"D/C ","Pattern":"x 5 7 5 7 2","Notes":"C D Gb A","Type":"major triad (altered bass)"},
{"Name":"D/C ","Pattern":"x 0 0 2 1 2","Notes":"C D Gb A","Type":"major triad (altered bass)"},
{"Name":"D/C ","Pattern":"x 3 x 2 3 2","Notes":"C D Gb A","Type":"major triad (altered bass)"},
{"Name":"D/C ","Pattern":"x 5 7 5 7 5","Notes":"C D Gb A","Type":"major triad (altered bass)"},
{"Name":"D/Db ","Pattern":"x x 0 14 14 14","Notes":"Db D Gb A","Type":"major triad (altered bass)"},
{"Name":"D/Db ","Pattern":"x x 0 2 2 2","Notes":"Db D Gb A","Type":"major triad (altered bass)"},
{"Name":"D/E ","Pattern":"0 0 0 2 3 2","Notes":"D E Gb A","Type":"major triad (altered bass)"},
{"Name":"D/E ","Pattern":"0 0 4 2 3 0","Notes":"D E Gb A","Type":"major triad (altered bass)"},
{"Name":"D/E ","Pattern":"2 x 0 2 3 0","Notes":"D E Gb A","Type":"major triad (altered bass)"},
{"Name":"D/E ","Pattern":"x 0 2 2 3 2","Notes":"D E Gb A","Type":"major triad (altered bass)"},
{"Name":"D/E ","Pattern":"x x 2 2 3 2","Notes":"D E Gb A","Type":"major triad (altered bass)"},
{"Name":"D/E ","Pattern":"x 5 4 2 3 0","Notes":"D E Gb A","Type":"major triad (altered bass)"},
{"Name":"D/E ","Pattern":"x 9 7 7 x 0","Notes":"D E Gb A","Type":"major triad (altered bass)"},
{"Name":"D/G ","Pattern":"5 x 4 0 3 5","Notes":"D Gb G A","Type":"major triad (altered bass)"},
{"Name":"D/G ","Pattern":"3 x 0 2 3 2","Notes":"D Gb G A","Type":"major triad (altered bass)"},
{"Name":"D5 or D(no 3rd) ","Pattern":"5 5 7 7 x 5","Notes":"D A","Type":"root and 5th (power chord)"},
{"Name":"D5 or D(no 3rd) ","Pattern":"x 0 0 2 3 5","Notes":"D A","Type":"root and 5th (power chord)"},
{"Name":"D6 ","Pattern":"x 0 4 4 3 2","Notes":"D Gb A B","Type":"major triad plus 6th"},
{"Name":"D6 ","Pattern":"x 2 0 2 0 2","Notes":"D Gb A B","Type":"major triad plus 6th"},
{"Name":"D6 ","Pattern":"x 2 0 2 3 2","Notes":"D Gb A B","Type":"major triad plus 6th"},
{"Name":"D6 ","Pattern":"x 2 4 2 3 2","Notes":"D Gb A B","Type":"major triad plus 6th"},
{"Name":"D6 ","Pattern":"x x 0 2 0 2","Notes":"D Gb A B","Type":"major triad plus 6th"},
{"Name":"D6/add9 or D6/9 ","Pattern":"0 0 2 4 3 2","Notes":"D E Gb A B","Type":"major triad plus 6th and 9th"},
{"Name":"D6/add9 or D6/9 ","Pattern":"0 2 0 2 0 2","Notes":"D E Gb A B","Type":"major triad plus 6th and 9th"},
{"Name":"D7 or Ddom 7 ","Pattern":"x 5 7 5 7 2","Notes":"C D Gb A","Type":"major triad minor 7th"},
{"Name":"D7 or Ddom 7 ","Pattern":"x 0 0 2 1 2","Notes":"C D Gb A","Type":"major triad minor 7th"},
{"Name":"D7 or Ddom 7 ","Pattern":"x 3 x 2 3 2","Notes":"C D Gb A","Type":"major triad minor 7th"},
{"Name":"D7 or Ddom 7 ","Pattern":"x 5 7 5 7 5","Notes":"C D Gb A","Type":"major triad minor 7th"},
{"Name":"D7sus4 ","Pattern":"x 5 7 5 8 3","Notes":"C D G A","Type":"sus4 triad minor 7th"},
{"Name":"D7sus4 ","Pattern":"x x 0 2 1 3","Notes":"C D G A","Type":"sus4 triad minor 7th"},
{"Name":"D9 or Ddom 9 ","Pattern":"0 0 0 2 1 2","Notes":"C D E Gb A","Type":"major triad minor 7th plus 9th"},
{"Name":"D9 or Ddom 9 ","Pattern":"2 x 0 2 1 0","Notes":"C D E Gb A","Type":"major triad minor 7th plus 9th"},
{"Name":"D9 or Ddom 9 ","Pattern":"x 5 7 5 7 0","Notes":"C D E Gb A","Type":"major triad minor 7th plus 9th"},
{"Name":"D9(#5) ","Pattern":"0 3 x 3 3 2","Notes":"C D E Gb Bb","Type":"augmented 5th minor 7th plus 9th"},
{"Name":"Dadd9 or D2 ","Pattern":"0 0 0 2 3 2","Notes":"D E Gb A","Type":"major triad plus 9th"},
{"Name":"Dadd9 or D2 ","Pattern":"0 0 4 2 3 0","Notes":"D E Gb A","Type":"major triad plus 9th"},
{"Name":"Dadd9 or D2 ","Pattern":"2 x 0 2 3 0","Notes":"D E Gb A","Type":"major triad plus 9th"},
{"Name":"Dadd9 or D2 ","Pattern":"x 0 2 2 3 2","Notes":"D E Gb A","Type":"major triad plus 9th"},
{"Name":"Dadd9 or D2 ","Pattern":"x x 2 2 3 2","Notes":"D E Gb A","Type":"major triad plus 9th"},
{"Name":"Dadd9 or D2 ","Pattern":"x 5 4 2 3 0","Notes":"D E Gb A","Type":"major triad plus 9th"},
{"Name":"Dadd9 or D2 ","Pattern":"x 9 7 7 x 0","Notes":"D E Gb A","Type":"major triad plus 9th"},
{"Name":"Daug/E ","Pattern":"2 x 4 3 3 0","Notes":"D E Gb Bb","Type":"augmented triad (altered bass)"},
{"Name":"Db or Dbmaj ","Pattern":"4 4 6 6 6 4","Notes":"Db F Ab","Type":"major triad"},
{"Name":"Db or Dbmaj ","Pattern":"x 4 3 1 2 1","Notes":"Db F Ab","Type":"major triad"},
{"Name":"Db or Dbmaj ","Pattern":"x 4 6 6 6 4","Notes":"Db F Ab","Type":"major triad"},
{"Name":"Db or Dbmaj ","Pattern":"x x 3 1 2 1","Notes":"Db F Ab","Type":"major triad"},
{"Name":"Db or Dbmaj ","Pattern":"x x 6 6 6 4","Notes":"Db F Ab","Type":"major triad"},
{"Name":"Db #5 or Dbaug ","Pattern":"x 0 3 2 2 1","Notes":"Db F A","Type":"augmented triad"},
{"Name":"Db #5 or Dbaug ","Pattern":"x 0 x 2 2 1","Notes":"Db F A","Type":"augmented triad"},
{"Name":"Db b5 ","Pattern":"x x 3 0 2 1","Notes":"Db F G","Type":"flat 5th"},
{"Name":"Db/B ","Pattern":"x 4 3 4 0 4","Notes":"Db F Ab B","Type":"major triad (altered bass)"},
{"Name":"Db/Bb ","Pattern":"x 1 3 1 2 1","Notes":"Db F Ab Bb","Type":"major triad (altered bass)"},
{"Name":"Db/C ","Pattern":"x 3 3 1 2 1","Notes":"C Db F Ab","Type":"major triad (altered bass)"},
{"Name":"Db/C ","Pattern":"x 4 6 5 6 4","Notes":"C Db F Ab","Type":"major triad (altered bass)"},
{"Name":"Db5 or Db(no 3rd)","Pattern":"x 4 6 6 x 4","Notes":"Db Ab","Type":"root and 5th (power chord)"},
{"Name":"Db6 ","Pattern":"x 1 3 1 2 1","Notes":"Db F Ab Bb","Type":"major triad plus 6th"},
{"Name":"Db7 or Dbdom 7 ","Pattern":"x 4 3 4 0 4","Notes":"Db F Ab B","Type":"major triad minor 7th"},
{"Name":"Dbaug/D ","Pattern":"x x 0 2 2 1","Notes":"Db D F A","Type":"augmented triad (altered bass)"},
{"Name":"Dbaug/G ","Pattern":"1 0 3 0 2 1","Notes":"Db F G A","Type":"augmented triad (altered bass)"},
{"Name":"Dbdim/A ","Pattern":"3 x 2 2 2 0","Notes":"Db E G A","Type":"diminished triad (altered bass)"},
{"Name":"Dbdim/A ","Pattern":"x 0 2 0 2 0","Notes":"Db E G A","Type":"diminished triad (altered bass)"},
{"Name":"Dbdim/A ","Pattern":"x 0 2 2 2 3","Notes":"Db E G A","Type":"diminished triad (altered bass)"},
{"Name":"Dbdim/B ","Pattern":"0 2 2 0 2 0","Notes":"Db E G B","Type":"diminished triad (altered bass)"},
{"Name":"Dbdim/Bb ","Pattern":"x 1 2 0 2 0","Notes":"Db E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Dbdim/Bb ","Pattern":"x x 2 3 2 3","Notes":"Db E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Dbdim/D ","Pattern":"3 x 0 0 2 0","Notes":"Db D E G","Type":"diminished triad (altered bass)"},
{"Name":"Dbdim/D ","Pattern":"x x 0 0 2 0","Notes":"Db D E G","Type":"diminished triad (altered bass)"},
{"Name":"Dbdim7 ","Pattern":"x 1 2 0 2 0","Notes":"Db E G Bb","Type":"diminished triad diminished 7th"},
{"Name":"Dbdim7 ","Pattern":"x x 2 3 2 3","Notes":"Db E G Bb","Type":"diminished triad diminished 7th"},
{"Name":"Dbm ","Pattern":"x 4 6 6 5 4","Notes":"Db E Ab","Type":"minor triad"},
{"Name":"Dbm ","Pattern":"x x 2 1 2 0","Notes":"Db E Ab","Type":"minor triad"},
{"Name":"Dbm ","Pattern":"x 4 6 6 x 0","Notes":"Db E Ab","Type":"minor triad"},
{"Name":"Dbm/A ","Pattern":"x 0 2 1 2 0","Notes":"Db E Ab A","Type":"minor triad (altered bass)"},
{"Name":"Dbm/B ","Pattern":"0 2 2 1 2 0","Notes":"Db E Ab B","Type":"minor triad (altered bass)"},
{"Name":"Dbm/B ","Pattern":"x 4 6 4 5 4","Notes":"Db E Ab B","Type":"minor triad (altered bass)"},
{"Name":"Dbm7 ","Pattern":"0 2 2 1 2 0","Notes":"Db E Ab B","Type":"minor triad minor 7th"},
{"Name":"Dbm7 ","Pattern":"x 4 6 4 5 4","Notes":"Db E Ab B","Type":"minor triad minor 7th"},
{"Name":"Dbm7(b5) or Dbo7 ","Pattern":"0 2 2 0 2 0","Notes":"Db E G B","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Dbmaj7 or Db#7 ","Pattern":"x 3 3 1 2 1","Notes":"C Db F Ab","Type":"major triad major 7th"},
{"Name":"Dbmaj7 or Db#7 ","Pattern":"x 4 6 5 6 4","Notes":"C Db F Ab","Type":"major triad major 7th"},
{"Name":"Dbsus2 or Dbadd9(no3) ","Pattern":"x x 6 6 4 4","Notes":"Db Eb Ab","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Dbsus4/Bb ","Pattern":"x x 4 3 2 4","Notes":"Db Gb Ab Bb","Type":"sus4 triad (altered bass)"},
{"Name":"Ddim/B ","Pattern":"x 2 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Ddim/B ","Pattern":"x x 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Ddim/B ","Pattern":"x x 3 4 3 4","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Ddim/Bb ","Pattern":"x 1 3 1 3 1","Notes":"D F Ab Bb","Type":"diminished triad (altered bass)"},
{"Name":"Ddim/Bb ","Pattern":"x x 3 3 3 4","Notes":"D F Ab Bb","Type":"diminished triad (altered bass)"},
{"Name":"Ddim/C ","Pattern":"x x 0 1 1 1","Notes":"C D F Ab","Type":"diminished triad (altered bass)"},
{"Name":"Ddim7 ","Pattern":"x 2 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Ddim7 ","Pattern":"x x 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Ddim7 ","Pattern":"x x 3 4 3 4","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Dm ","Pattern":"x 0 0 2 3 1","Notes":"D F A","Type":"minor triad"},
{"Name":"Dm/B ","Pattern":"1 2 3 2 3 1","Notes":"D F A B","Type":"minor triad (altered bass)"},
{"Name":"Dm/B ","Pattern":"x 2 0 2 0 1","Notes":"D F A B","Type":"minor triad (altered bass)"},
{"Name":"Dm/B ","Pattern":"x x 0 2 0 1","Notes":"D F A B","Type":"minor triad (altered bass)"},
{"Name":"Dm/Bb ","Pattern":"1 1 3 2 3 1","Notes":"D F A Bb","Type":"minor triad (altered bass)"},
{"Name":"Dm/C ","Pattern":"x 5 7 5 6 5","Notes":"C D F A","Type":"minor triad (altered bass)"},
{"Name":"Dm/C ","Pattern":"x x 0 2 1 1","Notes":"C D F A","Type":"minor triad (altered bass)"},
{"Name":"Dm/C ","Pattern":"x x 0 5 6 5","Notes":"C D F A","Type":"minor triad (altered bass)"},
{"Name":"Dm/Db ","Pattern":"x x 0 2 2 1","Notes":"Db D F A","Type":"minor triad (altered bass)"},
{"Name":"Dm/E ","Pattern":"x x 7 7 6 0","Notes":"D E F A","Type":"minor triad (altered bass)"},
{"Name":"Dm6 ","Pattern":"1 2 3 2 3 1","Notes":"D F A B","Type":"minor triad plus 6th"},
{"Name":"Dm6 ","Pattern":"x 2 0 2 0 1","Notes":"D F A B","Type":"minor triad plus 6th"},
{"Name":"Dm6 ","Pattern":"x x 0 2 0 1","Notes":"D F A B","Type":"minor triad plus 6th"},
{"Name":"Dm7 ","Pattern":"x 5 7 5 6 5","Notes":"C D F A","Type":"minor triad minor 7th"},
{"Name":"Dm7 ","Pattern":"x x 0 2 1 1","Notes":"C D F A","Type":"minor triad minor 7th"},
{"Name":"Dm7 ","Pattern":"x x 0 5 6 5","Notes":"C D F A","Type":"minor triad minor 7th"},
{"Name":"Dm7(b5) or Do7 ","Pattern":"x x 0 1 1 1","Notes":"C D F Ab","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Dm7/add11 or Dm7/11 ","Pattern":"3 x 0 2 1 1","Notes":"C D F G A","Type":"minor triad minor 7th plus 11th"},
{"Name":"Dmaj7 or D#7 ","Pattern":"x x 0 14 14 14","Notes":"Db D Gb A","Type":"major triad major 7th"},
{"Name":"Dmaj7 or D#7 ","Pattern":"x x 0 2 2 2","Notes":"Db D Gb A","Type":"major triad major 7th"},
{"Name":"Dmin/maj7 ","Pattern":"x x 0 2 2 1","Notes":"Db D F A","Type":"minor triad major 7th"},
{"Name":"Dsus or Dsus4 ","Pattern":"5 x 0 0 3 5","Notes":"D G A","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Dsus or Dsus4 ","Pattern":"3 0 0 0 3 3","Notes":"D G A","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Dsus or Dsus4 ","Pattern":"x 0 0 0 3 3","Notes":"D G A","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Dsus or Dsus4 ","Pattern":"x x 0 2 3 3","Notes":"D G A","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Dsus2 or Dadd9(no3)","Pattern":"5 5 7 7 x 0","Notes":"D E A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Dsus2 or Dadd9(no3)","Pattern":"x 0 0 2 3 0","Notes":"D E A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Dsus2 or Dadd9(no3)","Pattern":"0 0 2 2 3 0","Notes":"D E A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Dsus2 or Dadd9(no3)","Pattern":"x 0 2 2 3 0","Notes":"D E A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Dsus2 or Dadd9(no3)","Pattern":"x x 0 2 3 0","Notes":"D E A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Dsus2/Ab ","Pattern":"4 x 0 2 3 0","Notes":"D E Ab A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/B ","Pattern":"0 2 0 2 0 0","Notes":"D E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/B ","Pattern":"x 2 0 2 3 0","Notes":"D E A B","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Bb ","Pattern":"0 1 x 2 3 0","Notes":"D E A Bb","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/C ","Pattern":"x x 0 2 1 0","Notes":"C D E A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/C ","Pattern":"x x 0 5 5 5","Notes":"C D E A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Db ","Pattern":"x 0 0 2 2 0","Notes":"Db D E A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Db ","Pattern":"x x 0 2 2 0","Notes":"Db D E A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Db ","Pattern":"x x 0 6 5 5","Notes":"Db D E A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Db ","Pattern":"x x 0 9 10 9","Notes":"Db D E A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/F ","Pattern":"x x 7 7 6 0","Notes":"D E F A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/G ","Pattern":"x 0 2 0 3 0","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/G ","Pattern":"x 0 2 0 3 3","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/G ","Pattern":"x 0 2 2 3 3","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/G ","Pattern":"5 x 0 0 3 0","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/G ","Pattern":"x 0 0 0 x 0","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Gb ","Pattern":"0 0 0 2 3 2","Notes":"D E Gb A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Gb ","Pattern":"0 0 4 2 3 0","Notes":"D E Gb A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Gb ","Pattern":"2 x 0 2 3 0","Notes":"D E Gb A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Gb ","Pattern":"x 0 2 2 3 2","Notes":"D E Gb A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Gb ","Pattern":"x x 2 2 3 2","Notes":"D E Gb A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Gb ","Pattern":"x 5 4 2 3 0","Notes":"D E Gb A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus2/Gb ","Pattern":"x 9 7 7 x 0","Notes":"D E Gb A","Type":"sus2 triad (altered bass)"},
{"Name":"Dsus4/B ","Pattern":"3 0 0 0 0 3","Notes":"D G A B","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/B ","Pattern":"3 2 0 2 0 3","Notes":"D G A B","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/C ","Pattern":"x 5 7 5 8 3","Notes":"C D G A","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/C ","Pattern":"x x 0 2 1 3","Notes":"C D G A","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/E ","Pattern":"x 0 2 0 3 0","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/E ","Pattern":"x 0 2 0 3 3","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/E ","Pattern":"x 0 2 2 3 3","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/E ","Pattern":"5 x 0 0 3 0","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/E ","Pattern":"x 0 0 0 x 0","Notes":"D E G A","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/Gb ","Pattern":"5 x 4 0 3 5","Notes":"D Gb G A","Type":"sus4 triad (altered bass)"},
{"Name":"Dsus4/Gb ","Pattern":"3 x 0 2 3 2","Notes":"D Gb G A","Type":"sus4 triad (altered bass)"},
{"Name":"E or Emaj ","Pattern":"0 2 2 1 0 0","Notes":"E Ab B","Type":"major triad"},
{"Name":"E or Emaj ","Pattern":"x 7 6 4 5 0","Notes":"E Ab B","Type":"major triad"},
{"Name":"E #5 or Eaug ","Pattern":"x 3 2 1 1 0","Notes":"C E Ab","Type":"augmented triad"},
{"Name":"E/A ","Pattern":"x 0 2 1 0 0","Notes":"E Ab A B","Type":"major triad (altered bass)"},
{"Name":"E/D ","Pattern":"0 2 0 1 0 0","Notes":"D E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/D ","Pattern":"0 2 2 1 3 0","Notes":"D E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/D ","Pattern":"x 2 0 1 3 0","Notes":"D E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/D ","Pattern":"x x 0 1 0 0","Notes":"D E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/Db ","Pattern":"0 2 2 1 2 0","Notes":"Db E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/Db ","Pattern":"x 4 6 4 5 4","Notes":"Db E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/Eb ","Pattern":"0 2 1 1 0 0","Notes":"Eb E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/Eb ","Pattern":"0 x 6 4 4 0","Notes":"Eb E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/Eb ","Pattern":"x x 1 1 0 0","Notes":"Eb E Ab B","Type":"major triad (altered bass)"},
{"Name":"E/Gb ","Pattern":"0 2 2 1 0 2","Notes":"E Gb Ab B","Type":"major triad (altered bass)"},
{"Name":"E/Gb ","Pattern":"0 x 4 1 0 0","Notes":"E Gb Ab B","Type":"major triad (altered bass)"},
{"Name":"E/Gb ","Pattern":"2 2 2 1 0 0","Notes":"E Gb Ab B","Type":"major triad (altered bass)"},
{"Name":"E11/b9 ","Pattern":"0 0 3 4 3 4","Notes":"D E F Ab A B","Type":"major triad minor 7th flat 9th"},
{"Name":"E5 or E(no 3rd) ","Pattern":"0 2 x x x 0","Notes":"E B","Type":"root and 5th (power chord)"},
{"Name":"E5 or E(no 3rd) ","Pattern":"x 7 9 9 x 0","Notes":"E B","Type":"root and 5th (power chord)"},
{"Name":"E6 ","Pattern":"0 2 2 1 2 0","Notes":"Db E Ab B","Type":"major triad plus 6th"},
{"Name":"E6 ","Pattern":"x 4 6 4 5 4","Notes":"Db E Ab B","Type":"major triad plus 6th"},
{"Name":"E7 or Edom 7 ","Pattern":"0 2 0 1 0 0","Notes":"D E Ab B","Type":"major triad minor 7th"},
{"Name":"E7 or Edom 7 ","Pattern":"0 2 2 1 3 0","Notes":"D E Ab B","Type":"major triad minor 7th"},
{"Name":"E7 or Edom 7 ","Pattern":"x 2 0 1 3 0","Notes":"D E Ab B","Type":"major triad minor 7th"},
{"Name":"E7 or Edom 7 ","Pattern":"x x 0 1 0 0","Notes":"D E Ab B","Type":"major triad minor 7th"},
{"Name":"E7/add11 or E7/11 ","Pattern":"x 0 0 1 0 0","Notes":"D E Ab A B","Type":"major triad minor 7th plus 11th"},
{"Name":"E7/b9(b5) ","Pattern":"0 1 3 1 3 1","Notes":"D E F Ab Bb","Type":"diminished 5th minor 7th flat 9th"},
{"Name":"E7sus4 ","Pattern":"0 2 0 2 0 0","Notes":"D E A B","Type":"sus4 triad minor 7th"},
{"Name":"E9 or Edom 9 ","Pattern":"0 2 0 1 0 2","Notes":"D E Gb Ab B","Type":"major triad minor 7th plus 9th"},
{"Name":"E9 or Edom 9 ","Pattern":"2 2 0 1 0 0","Notes":"D E Gb Ab B","Type":"major triad minor 7th plus 9th"},
{"Name":"Eadd9 or E2 ","Pattern":"0 2 2 1 0 2","Notes":"E Gb Ab B","Type":"major triad plus 9th"},
{"Name":"Eadd9 or E2 ","Pattern":"0 x 4 1 0 0","Notes":"E Gb Ab B","Type":"major triad plus 9th"},
{"Name":"Eadd9 or E2 ","Pattern":"2 2 2 1 0 0","Notes":"E Gb Ab B","Type":"major triad plus 9th"},
{"Name":"Eb or Ebmaj ","Pattern":"x 1 1 3 4 3","Notes":"Eb G Bb","Type":"major triad"},
{"Name":"Eb or Ebmaj ","Pattern":"x x 1 3 4 3","Notes":"Eb G Bb","Type":"major triad"},
{"Name":"Eb or Ebmaj ","Pattern":"x x 5 3 4 3","Notes":"Eb G Bb","Type":"major triad"},
{"Name":"Eb #5 or Ebaug ","Pattern":"3 2 1 0 0 3","Notes":"Eb G B","Type":"augmented triad"},
{"Name":"Eb #5 or Ebaug ","Pattern":"3 x 1 0 0 3","Notes":"Eb G B","Type":"augmented triad"},
{"Name":"Eb/C ","Pattern":"x 3 5 3 4 3","Notes":"C Eb G Bb","Type":"major triad (altered bass)"},
{"Name":"Eb/D ","Pattern":"x 6 8 7 8 6","Notes":"D Eb G Bb","Type":"major triad (altered bass)"},
{"Name":"Eb/Db ","Pattern":"x 1 1 3 2 3","Notes":"Db Eb G Bb","Type":"major triad (altered bass)"},
{"Name":"Eb/Db ","Pattern":"x 6 8 6 8 6","Notes":"Db Eb G Bb","Type":"major triad (altered bass)"},
{"Name":"Eb/Db ","Pattern":"x x 1 3 2 3","Notes":"Db Eb G Bb","Type":"major triad (altered bass)"},
{"Name":"Eb/E ","Pattern":"x x 5 3 4 0","Notes":"Eb E G Bb","Type":"major triad (altered bass)"},
{"Name":"Eb5 or Eb(no 3rd)","Pattern":"x 6 8 8 x 6","Notes":"Eb Bb","Type":"root and 5th (power chord)"},
{"Name":"Eb6 ","Pattern":"x 3 5 3 4 3","Notes":"C Eb G Bb","Type":"major triad plus 6th"},
{"Name":"Eb7 or Ebdom 7 ","Pattern":"x 1 1 3 2 3","Notes":"Db Eb G Bb","Type":"major triad minor 7th"},
{"Name":"Eb7 or Ebdom 7 ","Pattern":"x 6 8 6 8 6","Notes":"Db Eb G Bb","Type":"major triad minor 7th"},
{"Name":"Eb7 or Ebdom 7 ","Pattern":"x x 1 3 2 3","Notes":"Db Eb G Bb","Type":"major triad minor 7th"},
{"Name":"Ebaug/E ","Pattern":"3 x 1 0 0 0","Notes":"Eb E G B","Type":"augmented triad (altered bass)"},
{"Name":"Ebaug/E ","Pattern":"x x 1 0 0 0","Notes":"Eb E G B","Type":"augmented triad (altered bass)"},
{"Name":"Ebdim/B ","Pattern":"2 x 1 2 0 2","Notes":"Eb Gb A B","Type":"diminished triad (altered bass)"},
{"Name":"Ebdim/B ","Pattern":"x 0 1 2 0 2","Notes":"Eb Gb A B","Type":"diminished triad (altered bass)"},
{"Name":"Ebdim/B ","Pattern":"x 2 1 2 0 2","Notes":"Eb Gb A B","Type":"diminished triad (altered bass)"},
{"Name":"Ebdim/B ","Pattern":"x 2 4 2 4 2","Notes":"Eb Gb A B","Type":"diminished triad (altered bass)"},
{"Name":"Ebdim/C ","Pattern":"x x 1 2 1 2","Notes":"C Eb Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Ebdim7 ","Pattern":"x x 1 2 1 2","Notes":"C Eb Gb A","Type":"diminished triad diminished 7th"},
{"Name":"Ebm ","Pattern":"x x 4 3 4 2","Notes":"Eb Gb Bb","Type":"minor triad"},
{"Name":"Ebm/Db ","Pattern":"x x 1 3 2 2","Notes":"Db Eb Gb Bb","Type":"minor triad (altered bass)"},
{"Name":"Ebm7 ","Pattern":"x x 1 3 2 2","Notes":"Db Eb Gb Bb","Type":"minor triad minor 7th"},
{"Name":"Ebmaj7 or Eb#7 ","Pattern":"x 6 8 7 8 6","Notes":"D Eb G Bb","Type":"major triad major 7th"},
{"Name":"Ebsus2/Ab ","Pattern":"x 1 3 1 4 1","Notes":"Eb F Ab Bb","Type":"sus2 triad (altered bass)"},
{"Name":"Ebsus4/F ","Pattern":"x 1 3 1 4 1","Notes":"Eb F Ab Bb","Type":"sus4 triad (altered bass)"},
{"Name":"Edim/C ","Pattern":"x 3 5 3 5 3","Notes":"C E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Edim/D ","Pattern":"3 x 0 3 3 0","Notes":"D E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Edim/Db ","Pattern":"x 1 2 0 2 0","Notes":"Db E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Edim/Db ","Pattern":"x x 2 3 2 3","Notes":"Db E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Edim/Eb ","Pattern":"x x 5 3 4 0","Notes":"Eb E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Edim7 ","Pattern":"x 1 2 0 2 0","Notes":"Db E G Bb","Type":"diminished triad diminished 7th"},
{"Name":"Edim7 ","Pattern":"x x 2 3 2 3","Notes":"Db E G Bb","Type":"diminished triad diminished 7th"},
{"Name":"Em ","Pattern":"0 2 2 0 0 0","Notes":"E G B","Type":"minor triad"},
{"Name":"Em ","Pattern":"3 x 2 0 0 0","Notes":"E G B","Type":"minor triad"},
{"Name":"Em ","Pattern":"x 2 5 x x 0","Notes":"E G B","Type":"minor triad"},
{"Name":"Em/A ","Pattern":"3 x 2 2 0 0","Notes":"E G A B","Type":"minor triad (altered bass)"},
{"Name":"Em/A ","Pattern":"x 0 2 0 0 0","Notes":"E G A B","Type":"minor triad (altered bass)"},
{"Name":"Em/A ","Pattern":"x 0 5 4 5 0","Notes":"E G A B","Type":"minor triad (altered bass)"},
{"Name":"Em/C ","Pattern":"0 3 2 0 0 0","Notes":"C E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/C ","Pattern":"x 2 2 0 1 0","Notes":"C E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/C ","Pattern":"x 3 5 4 5 3","Notes":"C E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"0 2 0 0 0 0","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"0 2 0 0 3 0","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"0 2 2 0 3 0","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"0 2 2 0 3 3","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"x x 0 12 12 12","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"x x 0 9 8 7","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"x x 2 4 3 3","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"0 x 0 0 0 0","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/D ","Pattern":"x 10 12 12 12 0","Notes":"D E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/Db ","Pattern":"0 2 2 0 2 0","Notes":"Db E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/Eb ","Pattern":"3 x 1 0 0 0","Notes":"Eb E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/Eb ","Pattern":"x x 1 0 0 0","Notes":"Eb E G B","Type":"minor triad (altered bass)"},
{"Name":"Em/Gb ","Pattern":"0 2 2 0 0 2","Notes":"E Gb G B","Type":"minor triad (altered bass)"},
{"Name":"Em/Gb ","Pattern":"0 2 4 0 0 0","Notes":"E Gb G B","Type":"minor triad (altered bass)"},
{"Name":"Em/Gb ","Pattern":"0 x 4 0 0 0","Notes":"E Gb G B","Type":"minor triad (altered bass)"},
{"Name":"Em/Gb ","Pattern":"2 2 2 0 0 0","Notes":"E Gb G B","Type":"minor triad (altered bass)"},
{"Name":"Em6 ","Pattern":"0 2 2 0 2 0","Notes":"Db E G B","Type":"minor triad plus 6th"},
{"Name":"Em7 ","Pattern":"0 2 0 0 0 0","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"0 2 0 0 3 0","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"0 2 2 0 3 0","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"0 2 2 0 3 3","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"x x 0 0 0 0","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"x x 0 12 12 12","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"x x 0 9 8 7","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"x x 2 4 3 3","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"0 x 0 0 0 0","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7 ","Pattern":"x 10 12 12 12 0","Notes":"D E G B","Type":"minor triad minor 7th"},
{"Name":"Em7(b5) or Eo7 ","Pattern":"3 x 0 3 3 0","Notes":"D E G Bb","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Em7/add11 or Em7/11 ","Pattern":"0 0 0 0 0 0","Notes":"D E G A B","Type":"minor triad minor 7th plus 11th"},
{"Name":"Em7/add11 or Em7/11 ","Pattern":"0 0 0 0 0 3","Notes":"D E G A B","Type":"minor triad minor 7th plus 11th"},
{"Name":"Em7/add11 or Em7/11 ","Pattern":"3 x 0 2 0 0","Notes":"D E G A B","Type":"minor triad minor 7th plus 11th"},
{"Name":"Em9 ","Pattern":"0 2 0 0 0 2","Notes":"D E Gb G B","Type":"minor triad minor 7th plus 9th"},
{"Name":"Em9 ","Pattern":"0 2 0 0 3 2","Notes":"D E Gb G B","Type":"minor triad minor 7th plus 9th"},
{"Name":"Em9 ","Pattern":"2 2 0 0 0 0","Notes":"D E Gb G B","Type":"minor triad minor 7th plus 9th"},
{"Name":"Emaj7 or E#7 ","Pattern":"0 2 1 1 0 0","Notes":"Eb E Ab B","Type":"major triad major 7th"},
{"Name":"Emaj7 or E#7 ","Pattern":"0 x 6 4 4 0","Notes":"Eb E Ab B","Type":"major triad major 7th"},
{"Name":"Emaj7 or E#7 ","Pattern":"x x 1 1 0 0","Notes":"Eb E Ab B","Type":"major triad major 7th"},
{"Name":"Emaj9 or E9(#7) ","Pattern":"0 2 1 1 0 2","Notes":"Eb E Gb Ab B","Type":"major triad major 7th plus 9th"},
{"Name":"Emaj9 or E9(#7) ","Pattern":"4 x 4 4 4 0","Notes":"Eb E Gb Ab B","Type":"major triad major 7th plus 9th"},
{"Name":"Emin/maj7 ","Pattern":"3 x 1 0 0 0","Notes":"Eb E G B","Type":"minor triad major 7th"},
{"Name":"Emin/maj7 ","Pattern":"x x 1 0 0 0","Notes":"Eb E G B","Type":"minor triad major 7th"},
{"Name":"Emin/maj9 ","Pattern":"0 6 4 0 0 0","Notes":"Eb E Gb G B","Type":"minor triad major 7th plus 9th"},
{"Name":"Esus or Esus4 ","Pattern":"0 0 2 2 0 0","Notes":"E A B","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Esus or Esus4 ","Pattern":"0 0 2 4 0 0","Notes":"E A B","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Esus or Esus4 ","Pattern":"0 2 2 2 0 0","Notes":"E A B","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Esus or Esus4 ","Pattern":"x 0 2 2 0 0","Notes":"E A B","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Esus or Esus4 ","Pattern":"x x 2 2 0 0","Notes":"E A B","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Esus2 or Eadd9(no3)","Pattern":"7 9 9 x x 0","Notes":"E Gb B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Esus2 or Eadd9(no3)","Pattern":"x 2 4 4 x 0","Notes":"E Gb B","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Esus2/A ","Pattern":"x 0 4 4 0 0","Notes":"E Gb A B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/A ","Pattern":"x 2 4 2 5 2","Notes":"E Gb A B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/Ab ","Pattern":"0 2 2 1 0 2","Notes":"E Gb Ab B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/Ab ","Pattern":"0 x 4 1 0 0","Notes":"E Gb Ab B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/Ab ","Pattern":"2 2 2 1 0 0","Notes":"E Gb Ab B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/Db ","Pattern":"x 4 4 4 x 0","Notes":"Db E Gb B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/Eb ","Pattern":"x 2 2 4 4 2","Notes":"Eb E Gb B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/Eb ","Pattern":"x x 4 4 4 0","Notes":"Eb E Gb B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/G ","Pattern":"0 2 2 0 0 2","Notes":"E Gb G B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/G ","Pattern":"0 2 4 0 0 0","Notes":"E Gb G B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/G ","Pattern":"0 x 4 0 0 0","Notes":"E Gb G B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus2/G ","Pattern":"2 2 2 0 0 0","Notes":"E Gb G B","Type":"sus2 triad (altered bass)"},
{"Name":"Esus4/Ab ","Pattern":"x 0 2 1 0 0","Notes":"E Ab A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/C ","Pattern":"0 0 7 5 0 0","Notes":"C E A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/C ","Pattern":"x 3 2 2 0 0","Notes":"C E A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/D ","Pattern":"0 2 0 2 0 0","Notes":"D E A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/D ","Pattern":"x 2 0 2 3 0","Notes":"D E A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/Db ","Pattern":"0 0 2 4 2 0","Notes":"Db E A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/Db ","Pattern":"x 0 7 6 0 0","Notes":"Db E A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/Eb ","Pattern":"x 2 1 2 0 0","Notes":"Eb E A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/F ","Pattern":"0 0 3 2 0 0","Notes":"E F A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/G ","Pattern":"3 x 2 2 0 0","Notes":"E G A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/G ","Pattern":"x 0 2 0 0 0","Notes":"E G A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/G ","Pattern":"x 0 5 4 5 0","Notes":"E G A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/Gb ","Pattern":"x 0 4 4 0 0","Notes":"E Gb A B","Type":"sus4 triad (altered bass)"},
{"Name":"Esus4/Gb ","Pattern":"x 2 4 2 5 2","Notes":"E Gb A B","Type":"sus4 triad (altered bass)"},
{"Name":"F or Fmaj ","Pattern":"1 3 3 2 1 1","Notes":"C F A","Type":"major triad"},
{"Name":"F or Fmaj ","Pattern":"x 0 3 2 1 1","Notes":"C F A","Type":"major triad"},
{"Name":"F or Fmaj ","Pattern":"x 3 3 2 1 1","Notes":"C F A","Type":"major triad"},
{"Name":"F or Fmaj ","Pattern":"x x 3 2 1 1","Notes":"C F A","Type":"major triad"},
{"Name":"F #5 or Faug ","Pattern":"x 0 3 2 2 1","Notes":"Db F A","Type":"augmented triad"},
{"Name":"F #5 or Faug ","Pattern":"x 0 x 2 2 1","Notes":"Db F A","Type":"augmented triad"},
{"Name":"F/D ","Pattern":"x 5 7 5 6 5","Notes":"C D F A","Type":"major triad (altered bass)"},
{"Name":"F/D ","Pattern":"x x 0 2 1 1","Notes":"C D F A","Type":"major triad (altered bass)"},
{"Name":"F/D ","Pattern":"x x 0 5 6 5","Notes":"C D F A","Type":"major triad (altered bass)"},
{"Name":"F/E ","Pattern":"0 0 3 2 1 0","Notes":"C E F A","Type":"major triad (altered bass)"},
{"Name":"F/E ","Pattern":"1 3 3 2 1 0","Notes":"C E F A","Type":"major triad (altered bass)"},
{"Name":"F/E ","Pattern":"1 x 2 2 1 0","Notes":"C E F A","Type":"major triad (altered bass)"},
{"Name":"F/E ","Pattern":"x x 2 2 1 1","Notes":"C E F A","Type":"major triad (altered bass)"},
{"Name":"F/E ","Pattern":"x x 3 2 1 0","Notes":"C E F A","Type":"major triad (altered bass)"},
{"Name":"F/Eb ","Pattern":"x x 1 2 1 1","Notes":"C Eb F A","Type":"major triad (altered bass)"},
{"Name":"F/Eb ","Pattern":"x x 3 5 4 5","Notes":"C Eb F A","Type":"major triad (altered bass)"},
{"Name":"F/G ","Pattern":"3 x 3 2 1 1","Notes":"C F G A","Type":"major triad (altered bass)"},
{"Name":"F/G ","Pattern":"x x 3 2 1 3","Notes":"C F G A","Type":"major triad (altered bass)"},
{"Name":"F5 or F(no 3rd) ","Pattern":"1 3 3 x x 1","Notes":"C F","Type":"root and 5th (power chord)"},
{"Name":"F5 or F(no 3rd) ","Pattern":"x 8 10 x x 1","Notes":"C F","Type":"root and 5th (power chord)"},
{"Name":"F6 ","Pattern":"x 5 7 5 6 5","Notes":"C D F A","Type":"major triad plus 6th"},
{"Name":"F6 ","Pattern":"x x 0 2 1 1","Notes":"C D F A","Type":"major triad plus 6th"},
{"Name":"F6 ","Pattern":"x x 0 5 6 5","Notes":"C D F A","Type":"major triad plus 6th"},
{"Name":"F6/add9 or F6/9 ","Pattern":"3 x 0 2 1 1","Notes":"C D F G A","Type":"major triad plus 6th and 9th"},
{"Name":"F7 or Fdom 7 ","Pattern":"x x 1 2 1 1","Notes":"C Eb F A","Type":"major triad minor 7th"},
{"Name":"F7 or Fdom 7 ","Pattern":"x x 3 5 4 5","Notes":"C Eb F A","Type":"major triad minor 7th"},
{"Name":"Fadd9 or F2 ","Pattern":"3 x 3 2 1 1","Notes":"C F G A","Type":"major triad plus 9th"},
{"Name":"Fadd9 or F2 ","Pattern":"x x 3 2 1 3","Notes":"C F G A","Type":"major triad plus 9th"},
{"Name":"Faug/D ","Pattern":"x x 0 2 2 1","Notes":"Db D F A","Type":"augmented triad (altered bass)"},
{"Name":"Faug/G ","Pattern":"1 0 3 0 2 1","Notes":"Db F G A","Type":"augmented triad (altered bass)"},
{"Name":"Fdim/D ","Pattern":"x 2 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Fdim/D ","Pattern":"x x 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Fdim/D ","Pattern":"x x 3 4 3 4","Notes":"D F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Fdim/Db ","Pattern":"x 4 3 4 0 4","Notes":"Db F Ab B","Type":"diminished triad (altered bass)"},
{"Name":"Fdim7 ","Pattern":"x 2 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Fdim7 ","Pattern":"x x 0 1 0 1","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Fdim7 ","Pattern":"x x 3 4 3 4","Notes":"D F Ab B","Type":"diminished triad diminished 7th"},
{"Name":"Fm ","Pattern":"x 3 3 1 1 1","Notes":"C F Ab","Type":"minor triad"},
{"Name":"Fm ","Pattern":"x x 3 1 1 1","Notes":"C F Ab","Type":"minor triad"},
{"Name":"Fm/D ","Pattern":"x x 0 1 1 1","Notes":"C D F Ab","Type":"minor triad (altered bass)"},
{"Name":"Fm/Db ","Pattern":"x 3 3 1 2 1","Notes":"C Db F Ab","Type":"minor triad (altered bass)"},
{"Name":"Fm/Db ","Pattern":"x 4 6 5 6 4","Notes":"C Db F Ab","Type":"minor triad (altered bass)"},
{"Name":"Fm/Eb ","Pattern":"x 8 10 8 9 8","Notes":"C Eb F Ab","Type":"minor triad (altered bass)"},
{"Name":"Fm/Eb ","Pattern":"x x 1 1 1 1","Notes":"C Eb F Ab","Type":"minor triad (altered bass)"},
{"Name":"Fm6 ","Pattern":"x x 0 1 1 1","Notes":"C D F Ab","Type":"minor triad plus 6th"},
{"Name":"Fm7 ","Pattern":"x 8 10 8 9 8","Notes":"C Eb F Ab","Type":"minor triad minor 7th"},
{"Name":"Fm7 ","Pattern":"x x 1 1 1 1","Notes":"C Eb F Ab","Type":"minor triad minor 7th"},
{"Name":"Fmaj7 or F#7 ","Pattern":"0 0 3 2 1 0","Notes":"C E F A","Type":"major triad major 7th"},
{"Name":"Fmaj7 or F#7 ","Pattern":"1 3 3 2 1 0","Notes":"C E F A","Type":"major triad major 7th"},
{"Name":"Fmaj7 or F#7 ","Pattern":"1 x 2 2 1 0","Notes":"C E F A","Type":"major triad major 7th"},
{"Name":"Fmaj7 or F#7 ","Pattern":"x x 2 2 1 1","Notes":"C E F A","Type":"major triad major 7th"},
{"Name":"Fmaj7 or F#7 ","Pattern":"x x 3 2 1 0","Notes":"C E F A","Type":"major triad major 7th"},
{"Name":"Fmaj7/#11 ","Pattern":"0 2 3 2 1 0","Notes":"C E F A B","Type":"major triad major 7th augmented 11th"},
{"Name":"Fmaj7/#11 ","Pattern":"1 3 3 2 0 0","Notes":"C E F A B","Type":"major triad major 7th augmented 11th"},
{"Name":"Fmaj9 or F9(#7) ","Pattern":"0 0 3 0 1 3","Notes":"C E F G A","Type":"major triad major 7th plus 9th"},
{"Name":"Fsus or Fsus4 ","Pattern":"x x 3 3 1 1","Notes":"C F Bb","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Fsus2 or Fadd9(no3)","Pattern":"x 3 3 0 1 1","Notes":"C F G","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Fsus2 or Fadd9(no3)","Pattern":"x x 3 0 1 1","Notes":"C F G","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Fsus2/A ","Pattern":"3 x 3 2 1 1","Notes":"C F G A","Type":"sus2 triad (altered bass)"},
{"Name":"Fsus2/A ","Pattern":"x x 3 2 1 3","Notes":"C F G A","Type":"sus2 triad (altered bass)"},
{"Name":"Fsus2/B ","Pattern":"x 3 3 0 0 3","Notes":"C F G B","Type":"sus2 triad (altered bass)"},
{"Name":"Fsus2/Bb ","Pattern":"x 3 5 3 6 3","Notes":"C F G Bb","Type":"sus2 triad (altered bass)"},
{"Name":"Fsus2/D ","Pattern":"3 3 0 0 1 1","Notes":"C D F G","Type":"sus2 triad (altered bass)"},
{"Name":"Fsus2/E ","Pattern":"x 3 3 0 1 0","Notes":"C E F G","Type":"sus2 triad (altered bass)"},
{"Name":"Fsus2/E ","Pattern":"x x 3 0 1 0","Notes":"C E F G","Type":"sus2 triad (altered bass)"},
{"Name":"Fsus4/G ","Pattern":"x 3 5 3 6 3","Notes":"C F G Bb","Type":"sus4 triad (altered bass)"},
{"Name":"G or Gmaj ","Pattern":"x 10 12 12 12 10","Notes":"D G B","Type":"major triad"},
{"Name":"G or Gmaj ","Pattern":"3 2 0 0 0 3","Notes":"D G B","Type":"major triad"},
{"Name":"G or Gmaj ","Pattern":"3 2 0 0 3 3","Notes":"D G B","Type":"major triad"},
{"Name":"G or Gmaj ","Pattern":"3 5 5 4 3 3","Notes":"D G B","Type":"major triad"},
{"Name":"G or Gmaj ","Pattern":"3 x 0 0 0 3","Notes":"D G B","Type":"major triad"},
{"Name":"G or Gmaj ","Pattern":"x 5 5 4 3 3","Notes":"D G B","Type":"major triad"},
{"Name":"G or Gmaj ","Pattern":"x x 0 4 3 3","Notes":"D G B","Type":"major triad"},
{"Name":"G or Gmaj ","Pattern":"x x 0 7 8 7","Notes":"D G B","Type":"major triad"},
{"Name":"G #5 or Gaug ","Pattern":"3 2 1 0 0 3","Notes":"Eb G B","Type":"augmented triad"},
{"Name":"G #5 or Gaug ","Pattern":"3 x 1 0 0 3","Notes":"Eb G B","Type":"augmented triad"},
{"Name":"G/A ","Pattern":"3 0 0 0 0 3","Notes":"D G A B","Type":"major triad (altered bass)"},
{"Name":"G/A ","Pattern":"3 2 0 2 0 3","Notes":"D G A B","Type":"major triad (altered bass)"},
{"Name":"G/C ","Pattern":"3 3 0 0 0 3","Notes":"C D G B","Type":"major triad (altered bass)"},
{"Name":"G/C ","Pattern":"x 3 0 0 0 3","Notes":"C D G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"0 2 0 0 0 0","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"0 2 0 0 3 0","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"0 2 2 0 3 0","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"0 2 2 0 3 3","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"x x 0 12 12 12","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"x x 0 9 8 7","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"x x 2 4 3 3","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"0 x 0 0 0 0","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/E ","Pattern":"x 10 12 12 12 0","Notes":"D E G B","Type":"major triad (altered bass)"},
{"Name":"G/F ","Pattern":"1 x 0 0 0 3","Notes":"D F G B","Type":"major triad (altered bass)"},
{"Name":"G/F ","Pattern":"3 2 0 0 0 1","Notes":"D F G B","Type":"major triad (altered bass)"},
{"Name":"G/F ","Pattern":"x x 0 0 0 1","Notes":"D F G B","Type":"major triad (altered bass)"},
{"Name":"G/Gb ","Pattern":"2 2 0 0 0 3","Notes":"D Gb G B","Type":"major triad (altered bass)"},
{"Name":"G/Gb ","Pattern":"2 2 0 0 3 3","Notes":"D Gb G B","Type":"major triad (altered bass)"},
{"Name":"G/Gb ","Pattern":"3 2 0 0 0 2","Notes":"D Gb G B","Type":"major triad (altered bass)"},
{"Name":"G/Gb ","Pattern":"x x 4 4 3 3","Notes":"D Gb G B","Type":"major triad (altered bass)"},
{"Name":"G5 or G(no 3rd) ","Pattern":"3 5 5 x x 3","Notes":"D G","Type":"root and 5th (power chord)"},
{"Name":"G5 or G(no 3rd) ","Pattern":"3 x 0 0 3 3","Notes":"D G","Type":"root and 5th (power chord)"},
{"Name":"G6 ","Pattern":"0 2 0 0 0 0","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6 ","Pattern":"0 2 0 0 3 0","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6 ","Pattern":"0 2 2 0 3 0","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6 ","Pattern":"0 2 2 0 3 3","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6 ","Pattern":"x x 0 12 12 12","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6 ","Pattern":"x x 0 9 8 7","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6 ","Pattern":"x x 2 4 3 3","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6 ","Pattern":"0 x 0 0 0 0","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6 ","Pattern":"x 10 12 12 12 0","Notes":"D E G B","Type":"major triad plus 6th"},
{"Name":"G6/add9 or G6/9 ","Pattern":"0 0 0 0 0 0","Notes":"D E G A B","Type":"major triad plus 6th and 9th"},
{"Name":"G6/add9 or G6/9 ","Pattern":"0 0 0 0 0 3","Notes":"D E G A B","Type":"major triad plus 6th and 9th"},
{"Name":"G6/add9 or G6/9 ","Pattern":"3 x 0 2 0 0","Notes":"D E G A B","Type":"major triad plus 6th and 9th"},
{"Name":"G7 or Gdom 7 ","Pattern":"1 x 0 0 0 3","Notes":"D F G B","Type":"major triad minor 7th"},
{"Name":"G7 or Gdom 7 ","Pattern":"3 2 0 0 0 1","Notes":"D F G B","Type":"major triad minor 7th"},
{"Name":"G7 or Gdom 7 ","Pattern":"x x 0 0 0 1","Notes":"D F G B","Type":"major triad minor 7th"},
{"Name":"G7/add11 or G7/11 ","Pattern":"x 3 0 0 0 1","Notes":"C D F G B","Type":"major triad minor 7th plus 11th"},
{"Name":"G7sus4 ","Pattern":"3 3 0 0 1 1","Notes":"C D F G","Type":"sus4 triad minor 7th"},
{"Name":"G9 or Gdom 9 ","Pattern":"x 0 0 0 0 1","Notes":"D F G A B","Type":"major triad minor 7th plus 9th"},
{"Name":"G9 or Gdom 9 ","Pattern":"x 2 3 2 3 3","Notes":"D F G A B","Type":"major triad minor 7th plus 9th"},
{"Name":"Gadd9 or G2 ","Pattern":"3 0 0 0 0 3","Notes":"D G A B","Type":"major triad plus 9th"},
{"Name":"Gadd9 or G2 ","Pattern":"3 2 0 2 0 3","Notes":"D G A B","Type":"major triad plus 9th"},
{"Name":"Gaug/E ","Pattern":"3 x 1 0 0 0","Notes":"Eb E G B","Type":"augmented triad (altered bass)"},
{"Name":"Gaug/E ","Pattern":"x x 1 0 0 0","Notes":"Eb E G B","Type":"augmented triad (altered bass)"},
{"Name":"Gb or Gbmaj ","Pattern":"2 4 4 3 2 2","Notes":"Db Gb Bb","Type":"major triad"},
{"Name":"Gb or Gbmaj ","Pattern":"x 4 4 3 2 2","Notes":"Db Gb Bb","Type":"major triad"},
{"Name":"Gb or Gbmaj ","Pattern":"x x 4 3 2 2","Notes":"Db Gb Bb","Type":"major triad"},
{"Name":"Gb #5 or Gbaug ","Pattern":"x x 0 3 3 2","Notes":"D Gb Bb","Type":"augmented triad"},
{"Name":"Gb/Ab ","Pattern":"x x 4 3 2 4","Notes":"Db Gb Ab Bb","Type":"major triad (altered bass)"},
{"Name":"Gb/E ","Pattern":"2 4 2 3 2 2","Notes":"Db E Gb Bb","Type":"major triad (altered bass)"},
{"Name":"Gb/E ","Pattern":"x x 4 3 2 0","Notes":"Db E Gb Bb","Type":"major triad (altered bass)"},
{"Name":"Gb/Eb ","Pattern":"x x 1 3 2 2","Notes":"Db Eb Gb Bb","Type":"major triad (altered bass)"},
{"Name":"Gb/F ","Pattern":"x x 3 3 2 2","Notes":"Db F Gb Bb","Type":"major triad (altered bass)"},
{"Name":"Gb6 ","Pattern":"x x 1 3 2 2","Notes":"Db Eb Gb Bb","Type":"major triad plus 6th"},
{"Name":"Gb7 or Gbdom 7 ","Pattern":"2 4 2 3 2 2","Notes":"Db E Gb Bb","Type":"major triad minor 7th"},
{"Name":"Gb7 or Gbdom 7 ","Pattern":"x x 4 3 2 0","Notes":"Db E Gb Bb","Type":"major triad minor 7th"},
{"Name":"Gb7(#5) ","Pattern":"2 x 4 3 3 0","Notes":"D E Gb Bb","Type":"minor 7th sharp 5th"},
{"Name":"Gb7/#9 ","Pattern":"x 0 4 3 2 0","Notes":"Db E Gb A Bb","Type":"major triad minor 7th augmented 9th"},
{"Name":"Gb7sus4 ","Pattern":"x 4 4 4 x 0","Notes":"Db E Gb B","Type":"sus4 triad minor 7th"},
{"Name":"Gbadd9 or Gb2 ","Pattern":"x x 4 3 2 4","Notes":"Db Gb Ab Bb","Type":"major triad plus 9th"},
{"Name":"Gbaug/E ","Pattern":"2 x 4 3 3 0","Notes":"D E Gb Bb","Type":"augmented triad (altered bass)"},
{"Name":"Gbdim/D ","Pattern":"x 5 7 5 7 2","Notes":"C D Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Gbdim/D ","Pattern":"x 0 0 2 1 2","Notes":"C D Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Gbdim/D ","Pattern":"x 3 x 2 3 2","Notes":"C D Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Gbdim/D ","Pattern":"x 5 7 5 7 5","Notes":"C D Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Gbdim/E ","Pattern":"x 0 2 2 1 2","Notes":"C E Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Gbdim/E ","Pattern":"x x 2 2 1 2","Notes":"C E Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Gbdim/Eb ","Pattern":"x x 1 2 1 2","Notes":"C Eb Gb A","Type":"diminished triad (altered bass)"},
{"Name":"Gbdim7 ","Pattern":"x x 1 2 1 2","Notes":"C Eb Gb A","Type":"diminished triad diminished 7th"},
{"Name":"Gbm ","Pattern":"2 4 4 2 2 2","Notes":"Db Gb A","Type":"minor triad"},
{"Name":"Gbm ","Pattern":"x 4 4 2 2 2","Notes":"Db Gb A","Type":"minor triad"},
{"Name":"Gbm ","Pattern":"x x 4 2 2 2","Notes":"Db Gb A","Type":"minor triad"},
{"Name":"Gbm/D ","Pattern":"x x 0 14 14 14","Notes":"Db D Gb A","Type":"minor triad (altered bass)"},
{"Name":"Gbm/D ","Pattern":"x x 0 2 2 2","Notes":"Db D Gb A","Type":"minor triad (altered bass)"},
{"Name":"Gbm/E ","Pattern":"0 0 2 2 2 2","Notes":"Db E Gb A","Type":"minor triad (altered bass)"},
{"Name":"Gbm/E ","Pattern":"0 x 4 2 2 0","Notes":"Db E Gb A","Type":"minor triad (altered bass)"},
{"Name":"Gbm/E ","Pattern":"2 x 2 2 2 0","Notes":"Db E Gb A","Type":"minor triad (altered bass)"},
{"Name":"Gbm/E ","Pattern":"x 0 4 2 2 0","Notes":"Db E Gb A","Type":"minor triad (altered bass)"},
{"Name":"Gbm/E ","Pattern":"x x 2 2 2 2","Notes":"Db E Gb A","Type":"minor triad (altered bass)"},
{"Name":"Gbm7 ","Pattern":"0 0 2 2 2 2","Notes":"Db E Gb A","Type":"minor triad minor 7th"},
{"Name":"Gbm7 ","Pattern":"0 x 4 2 2 0","Notes":"Db E Gb A","Type":"minor triad minor 7th"},
{"Name":"Gbm7 ","Pattern":"2 x 2 2 2 0","Notes":"Db E Gb A","Type":"minor triad minor 7th"},
{"Name":"Gbm7 ","Pattern":"x 0 4 2 2 0","Notes":"Db E Gb A","Type":"minor triad minor 7th"},
{"Name":"Gbm7 ","Pattern":"x x 2 2 2 2","Notes":"Db E Gb A","Type":"minor triad minor 7th"},
{"Name":"Gbm7(b5) or Gbo7 ","Pattern":"x 0 2 2 1 2","Notes":"C E Gb A","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Gbm7(b5) or Gbo7 ","Pattern":"x x 2 2 1 2","Notes":"C E Gb A","Type":"diminished triad minor 7th half-diminished 7th"},
{"Name":"Gbm7/b9 ","Pattern":"0 0 2 0 2 2","Notes":"Db E Gb G A","Type":"minor triad minor 7th flat 9th"},
{"Name":"Gbmaj7 or Gb#7 ","Pattern":"x x 3 3 2 2","Notes":"Db F Gb Bb","Type":"major triad major 7th"},
{"Name":"Gbsus or Gbsus4 ","Pattern":"x 4 4 4 2 2","Notes":"Db Gb B","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Gbsus2/Bb ","Pattern":"x x 4 3 2 4","Notes":"Db Gb Ab Bb","Type":"sus2 triad (altered bass)"},
{"Name":"Gbsus4/E ","Pattern":"x 4 4 4 x 0","Notes":"Db E Gb B","Type":"sus4 triad (altered bass)"},
{"Name":"Gdim/E ","Pattern":"x 1 2 0 2 0","Notes":"Db E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Gdim/E ","Pattern":"x x 2 3 2 3","Notes":"Db E G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Gdim/Eb ","Pattern":"x 1 1 3 2 3","Notes":"Db Eb G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Gdim/Eb ","Pattern":"x 6 8 6 8 6","Notes":"Db Eb G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Gdim/Eb ","Pattern":"x x 1 3 2 3","Notes":"Db Eb G Bb","Type":"diminished triad (altered bass)"},
{"Name":"Gdim7 ","Pattern":"x 1 2 0 2 0","Notes":"Db E G Bb","Type":"diminished triad diminished 7th"},
{"Name":"Gdim7 ","Pattern":"x x 2 3 2 3","Notes":"Db E G Bb","Type":"diminished triad diminished 7th"},
{"Name":"Gm ","Pattern":"3 5 5 3 3 3","Notes":"D G Bb","Type":"minor triad"},
{"Name":"Gm ","Pattern":"x x 0 3 3 3","Notes":"D G Bb","Type":"minor triad"},
{"Name":"Gm/E ","Pattern":"3 x 0 3 3 0","Notes":"D E G Bb","Type":"minor triad (altered bass)"},
{"Name":"Gm/Eb ","Pattern":"x 6 8 7 8 6","Notes":"D Eb G Bb","Type":"minor triad (altered bass)"},
{"Name":"Gm/F ","Pattern":"3 5 3 3 3 3","Notes":"D F G Bb","Type":"minor triad (altered bass)"},
{"Name":"Gm/F ","Pattern":"x x 3 3 3 3","Notes":"D F G Bb","Type":"minor triad (altered bass)"},
{"Name":"Gm13 ","Pattern":"0 0 3 3 3 3","Notes":"D E F G A Bb","Type":"minor triad minor 7th plus 9th and 13th"},
{"Name":"Gm6 ","Pattern":"3 x 0 3 3 0","Notes":"D E G Bb","Type":"minor triad plus 6th"},
{"Name":"Gm7 ","Pattern":"3 5 3 3 3 3","Notes":"D F G Bb","Type":"minor triad minor 7th"},
{"Name":"Gm7 ","Pattern":"x x 3 3 3 3","Notes":"D F G Bb","Type":"minor triad minor 7th"},
{"Name":"Gm7/add11 or Gm7/11 ","Pattern":"x 3 3 3 3 3","Notes":"C D F G Bb","Type":"minor triad minor 7th plus 11th"},
{"Name":"Gm9 ","Pattern":"3 5 3 3 3 5","Notes":"D F G A Bb","Type":"minor triad minor 7th plus 9th"},
{"Name":"Gmaj7 or G#7 ","Pattern":"2 2 0 0 0 3","Notes":"D Gb G B","Type":"major triad major 7th"},
{"Name":"Gmaj7 or G#7 ","Pattern":"2 2 0 0 3 3","Notes":"D Gb G B","Type":"major triad major 7th"},
{"Name":"Gmaj7 or G#7 ","Pattern":"3 2 0 0 0 2","Notes":"D Gb G B","Type":"major triad major 7th"},
{"Name":"Gmaj7 or G#7 ","Pattern":"x x 4 4 3 3","Notes":"D Gb G B","Type":"major triad major 7th"},
{"Name":"Gsus or Gsus4 ","Pattern":"x 10 12 12 13 3","Notes":"C D G","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Gsus or Gsus4 ","Pattern":"x 3 0 0 3 3","Notes":"C D G","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Gsus or Gsus4 ","Pattern":"x 3 5 5 3 3","Notes":"C D G","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Gsus or Gsus4 ","Pattern":"x 5 5 5 3 3","Notes":"C D G","Type":"no 3rd but a 4th from a major triad"},
{"Name":"Gsus2 or Gadd9(no3)","Pattern":"5 x 0 0 3 5","Notes":"D G A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Gsus2 or Gadd9(no3)","Pattern":"3 0 0 0 3 3","Notes":"D G A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Gsus2 or Gadd9(no3)","Pattern":"x 0 0 0 3 3","Notes":"D G A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Gsus2 or Gadd9(no3)","Pattern":"x x 0 2 3 3","Notes":"D G A","Type":"no 3rd but a 2nd from a major triad"},
{"Name":"Gsus2/B ","Pattern":"3 0 0 0 0 3","Notes":"D G A B","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/B ","Pattern":"3 2 0 2 0 3","Notes":"D G A B","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/C ","Pattern":"x 5 7 5 8 3","Notes":"C D G A","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/C ","Pattern":"x x 0 2 1 3","Notes":"C D G A","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/E ","Pattern":"x 0 2 0 3 0","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/E ","Pattern":"x 0 2 0 3 3","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/E ","Pattern":"x 0 2 2 3 3","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/E ","Pattern":"5 0 0 0 3 0","Notes":"D E G A","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/Gb ","Pattern":"5 x 4 0 3 5","Notes":"D Gb G A","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus2/Gb ","Pattern":"3 x 0 2 3 2","Notes":"D Gb G A","Type":"sus2 triad (altered bass)"},
{"Name":"Gsus4/A ","Pattern":"x 5 7 5 8 3","Notes":"C D G A","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/A ","Pattern":"x x 0 2 1 3","Notes":"C D G A","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/B ","Pattern":"3 3 0 0 0 3","Notes":"C D G B","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/B ","Pattern":"x 3 0 0 0 3","Notes":"C D G B","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/E ","Pattern":"3 x 0 0 1 0","Notes":"C D E G","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/E ","Pattern":"x 3 0 0 1 0","Notes":"C D E G","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/E ","Pattern":"x 3 2 0 3 0","Notes":"C D E G","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/E ","Pattern":"x 3 2 0 3 3","Notes":"C D E G","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/E ","Pattern":"x x 0 0 1 0","Notes":"C D E G","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/E ","Pattern":"x x 0 5 5 3","Notes":"C D E G","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/E ","Pattern":"x 10 12 12 13 0","Notes":"C D E G","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/E ","Pattern":"x 5 5 5 x 0","Notes":"C D E G","Type":"sus4 triad (altered bass)"},
{"Name":"Gsus4/F ","Pattern":"3 3 0 0 1 1","Notes":"C D F G","Type":"sus4 triad (altered bass)"}];